/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.enviroment.remoteAgent.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ProcessOutput implements org.apache.thrift.TBase<ProcessOutput, ProcessOutput._Fields>, java.io.Serializable, Cloneable, Comparable<ProcessOutput> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProcessOutput");

  private static final org.apache.thrift.protocol.TField STDOUT_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("stdoutData", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField STDERR_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("stderrData", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EXIT_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("exitCode", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ProcessOutputStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ProcessOutputTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer stdoutData; // optional
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer stderrData; // optional
  public int exitCode; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STDOUT_DATA((short)1, "stdoutData"),
    STDERR_DATA((short)2, "stderrData"),
    EXIT_CODE((short)3, "exitCode");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STDOUT_DATA
          return STDOUT_DATA;
        case 2: // STDERR_DATA
          return STDERR_DATA;
        case 3: // EXIT_CODE
          return EXIT_CODE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __EXITCODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.STDOUT_DATA, _Fields.STDERR_DATA, _Fields.EXIT_CODE};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STDOUT_DATA, new org.apache.thrift.meta_data.FieldMetaData("stdoutData", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.STDERR_DATA, new org.apache.thrift.meta_data.FieldMetaData("stderrData", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.EXIT_CODE, new org.apache.thrift.meta_data.FieldMetaData("exitCode", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProcessOutput.class, metaDataMap);
  }

  public ProcessOutput() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProcessOutput(ProcessOutput other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetStdoutData()) {
      this.stdoutData = org.apache.thrift.TBaseHelper.copyBinary(other.stdoutData);
    }
    if (other.isSetStderrData()) {
      this.stderrData = org.apache.thrift.TBaseHelper.copyBinary(other.stderrData);
    }
    this.exitCode = other.exitCode;
  }

  @Override
  public ProcessOutput deepCopy() {
    return new ProcessOutput(this);
  }

  @Override
  public void clear() {
    this.stdoutData = null;
    this.stderrData = null;
    setExitCodeIsSet(false);
    this.exitCode = 0;
  }

  public byte[] getStdoutData() {
    setStdoutData(org.apache.thrift.TBaseHelper.rightSize(stdoutData));
    return stdoutData == null ? null : stdoutData.array();
  }

  public java.nio.ByteBuffer bufferForStdoutData() {
    return org.apache.thrift.TBaseHelper.copyBinary(stdoutData);
  }

  public ProcessOutput setStdoutData(byte[] stdoutData) {
    this.stdoutData = stdoutData == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(stdoutData.clone());
    return this;
  }

  public ProcessOutput setStdoutData(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer stdoutData) {
    this.stdoutData = org.apache.thrift.TBaseHelper.copyBinary(stdoutData);
    return this;
  }

  public void unsetStdoutData() {
    this.stdoutData = null;
  }

  /** Returns true if field stdoutData is set (has been assigned a value) and false otherwise */
  public boolean isSetStdoutData() {
    return this.stdoutData != null;
  }

  public void setStdoutDataIsSet(boolean value) {
    if (!value) {
      this.stdoutData = null;
    }
  }

  public byte[] getStderrData() {
    setStderrData(org.apache.thrift.TBaseHelper.rightSize(stderrData));
    return stderrData == null ? null : stderrData.array();
  }

  public java.nio.ByteBuffer bufferForStderrData() {
    return org.apache.thrift.TBaseHelper.copyBinary(stderrData);
  }

  public ProcessOutput setStderrData(byte[] stderrData) {
    this.stderrData = stderrData == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(stderrData.clone());
    return this;
  }

  public ProcessOutput setStderrData(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer stderrData) {
    this.stderrData = org.apache.thrift.TBaseHelper.copyBinary(stderrData);
    return this;
  }

  public void unsetStderrData() {
    this.stderrData = null;
  }

  /** Returns true if field stderrData is set (has been assigned a value) and false otherwise */
  public boolean isSetStderrData() {
    return this.stderrData != null;
  }

  public void setStderrDataIsSet(boolean value) {
    if (!value) {
      this.stderrData = null;
    }
  }

  public int getExitCode() {
    return this.exitCode;
  }

  public ProcessOutput setExitCode(int exitCode) {
    this.exitCode = exitCode;
    setExitCodeIsSet(true);
    return this;
  }

  public void unsetExitCode() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EXITCODE_ISSET_ID);
  }

  /** Returns true if field exitCode is set (has been assigned a value) and false otherwise */
  public boolean isSetExitCode() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EXITCODE_ISSET_ID);
  }

  public void setExitCodeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EXITCODE_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case STDOUT_DATA:
      if (value == null) {
        unsetStdoutData();
      } else {
        if (value instanceof byte[]) {
          setStdoutData((byte[])value);
        } else {
          setStdoutData((java.nio.ByteBuffer)value);
        }
      }
      break;

    case STDERR_DATA:
      if (value == null) {
        unsetStderrData();
      } else {
        if (value instanceof byte[]) {
          setStderrData((byte[])value);
        } else {
          setStderrData((java.nio.ByteBuffer)value);
        }
      }
      break;

    case EXIT_CODE:
      if (value == null) {
        unsetExitCode();
      } else {
        setExitCode((Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STDOUT_DATA:
      return getStdoutData();

    case STDERR_DATA:
      return getStderrData();

    case EXIT_CODE:
      return getExitCode();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STDOUT_DATA:
      return isSetStdoutData();
    case STDERR_DATA:
      return isSetStderrData();
    case EXIT_CODE:
      return isSetExitCode();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof ProcessOutput)
      return this.equals((ProcessOutput)that);
    return false;
  }

  public boolean equals(ProcessOutput that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_stdoutData = true && this.isSetStdoutData();
    boolean that_present_stdoutData = true && that.isSetStdoutData();
    if (this_present_stdoutData || that_present_stdoutData) {
      if (!(this_present_stdoutData && that_present_stdoutData))
        return false;
      if (!this.stdoutData.equals(that.stdoutData))
        return false;
    }

    boolean this_present_stderrData = true && this.isSetStderrData();
    boolean that_present_stderrData = true && that.isSetStderrData();
    if (this_present_stderrData || that_present_stderrData) {
      if (!(this_present_stderrData && that_present_stderrData))
        return false;
      if (!this.stderrData.equals(that.stderrData))
        return false;
    }

    boolean this_present_exitCode = true && this.isSetExitCode();
    boolean that_present_exitCode = true && that.isSetExitCode();
    if (this_present_exitCode || that_present_exitCode) {
      if (!(this_present_exitCode && that_present_exitCode))
        return false;
      if (this.exitCode != that.exitCode)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetStdoutData()) ? 131071 : 524287);
    if (isSetStdoutData())
      hashCode = hashCode * 8191 + stdoutData.hashCode();

    hashCode = hashCode * 8191 + ((isSetStderrData()) ? 131071 : 524287);
    if (isSetStderrData())
      hashCode = hashCode * 8191 + stderrData.hashCode();

    hashCode = hashCode * 8191 + ((isSetExitCode()) ? 131071 : 524287);
    if (isSetExitCode())
      hashCode = hashCode * 8191 + exitCode;

    return hashCode;
  }

  @Override
  public int compareTo(ProcessOutput other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetStdoutData(), other.isSetStdoutData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStdoutData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stdoutData, other.stdoutData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetStderrData(), other.isSetStderrData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStderrData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stderrData, other.stderrData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetExitCode(), other.isSetExitCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExitCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.exitCode, other.exitCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ProcessOutput(");
    boolean first = true;

    if (isSetStdoutData()) {
      sb.append("stdoutData:");
      if (this.stdoutData == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.stdoutData, sb);
      }
      first = false;
    }
    if (isSetStderrData()) {
      if (!first) sb.append(", ");
      sb.append("stderrData:");
      if (this.stderrData == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.stderrData, sb);
      }
      first = false;
    }
    if (isSetExitCode()) {
      if (!first) sb.append(", ");
      sb.append("exitCode:");
      sb.append(this.exitCode);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProcessOutputStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ProcessOutputStandardScheme getScheme() {
      return new ProcessOutputStandardScheme();
    }
  }

  private static class ProcessOutputStandardScheme extends org.apache.thrift.scheme.StandardScheme<ProcessOutput> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ProcessOutput struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STDOUT_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.stdoutData = iprot.readBinary();
              struct.setStdoutDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STDERR_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.stderrData = iprot.readBinary();
              struct.setStderrDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EXIT_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.exitCode = iprot.readI32();
              struct.setExitCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ProcessOutput struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.stdoutData != null) {
        if (struct.isSetStdoutData()) {
          oprot.writeFieldBegin(STDOUT_DATA_FIELD_DESC);
          oprot.writeBinary(struct.stdoutData);
          oprot.writeFieldEnd();
        }
      }
      if (struct.stderrData != null) {
        if (struct.isSetStderrData()) {
          oprot.writeFieldBegin(STDERR_DATA_FIELD_DESC);
          oprot.writeBinary(struct.stderrData);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetExitCode()) {
        oprot.writeFieldBegin(EXIT_CODE_FIELD_DESC);
        oprot.writeI32(struct.exitCode);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProcessOutputTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ProcessOutputTupleScheme getScheme() {
      return new ProcessOutputTupleScheme();
    }
  }

  private static class ProcessOutputTupleScheme extends org.apache.thrift.scheme.TupleScheme<ProcessOutput> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProcessOutput struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetStdoutData()) {
        optionals.set(0);
      }
      if (struct.isSetStderrData()) {
        optionals.set(1);
      }
      if (struct.isSetExitCode()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetStdoutData()) {
        oprot.writeBinary(struct.stdoutData);
      }
      if (struct.isSetStderrData()) {
        oprot.writeBinary(struct.stderrData);
      }
      if (struct.isSetExitCode()) {
        oprot.writeI32(struct.exitCode);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProcessOutput struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.stdoutData = iprot.readBinary();
        struct.setStdoutDataIsSet(true);
      }
      if (incoming.get(1)) {
        struct.stderrData = iprot.readBinary();
        struct.setStderrDataIsSet(true);
      }
      if (incoming.get(2)) {
        struct.exitCode = iprot.readI32();
        struct.setExitCodeIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

