/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.enviroment.remoteAgent.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class StatInfo implements org.apache.thrift.TBase<StatInfo, StatInfo._Fields>, java.io.Serializable, Cloneable, Comparable<StatInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("StatInfo");

  private static final org.apache.thrift.protocol.TField CPU_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("cpuCount", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField CPU_LOAD_FIELD_DESC = new org.apache.thrift.protocol.TField("cpuLoad", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField TOTAL_MEMORY_FIELD_DESC = new org.apache.thrift.protocol.TField("totalMemory", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField USED_MEMORY_FIELD_DESC = new org.apache.thrift.protocol.TField("usedMemory", org.apache.thrift.protocol.TType.I64, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new StatInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new StatInfoTupleSchemeFactory();

  public int cpuCount; // required
  public double cpuLoad; // required
  public long totalMemory; // required
  public long usedMemory; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CPU_COUNT((short)1, "cpuCount"),
    CPU_LOAD((short)2, "cpuLoad"),
    TOTAL_MEMORY((short)3, "totalMemory"),
    USED_MEMORY((short)4, "usedMemory");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CPU_COUNT
          return CPU_COUNT;
        case 2: // CPU_LOAD
          return CPU_LOAD;
        case 3: // TOTAL_MEMORY
          return TOTAL_MEMORY;
        case 4: // USED_MEMORY
          return USED_MEMORY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CPUCOUNT_ISSET_ID = 0;
  private static final int __CPULOAD_ISSET_ID = 1;
  private static final int __TOTALMEMORY_ISSET_ID = 2;
  private static final int __USEDMEMORY_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CPU_COUNT, new org.apache.thrift.meta_data.FieldMetaData("cpuCount", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CPU_LOAD, new org.apache.thrift.meta_data.FieldMetaData("cpuLoad", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.TOTAL_MEMORY, new org.apache.thrift.meta_data.FieldMetaData("totalMemory", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USED_MEMORY, new org.apache.thrift.meta_data.FieldMetaData("usedMemory", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(StatInfo.class, metaDataMap);
  }

  public StatInfo() {
  }

  public StatInfo(
    int cpuCount,
    double cpuLoad,
    long totalMemory,
    long usedMemory)
  {
    this();
    this.cpuCount = cpuCount;
    setCpuCountIsSet(true);
    this.cpuLoad = cpuLoad;
    setCpuLoadIsSet(true);
    this.totalMemory = totalMemory;
    setTotalMemoryIsSet(true);
    this.usedMemory = usedMemory;
    setUsedMemoryIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public StatInfo(StatInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.cpuCount = other.cpuCount;
    this.cpuLoad = other.cpuLoad;
    this.totalMemory = other.totalMemory;
    this.usedMemory = other.usedMemory;
  }

  @Override
  public StatInfo deepCopy() {
    return new StatInfo(this);
  }

  @Override
  public void clear() {
    setCpuCountIsSet(false);
    this.cpuCount = 0;
    setCpuLoadIsSet(false);
    this.cpuLoad = 0.0;
    setTotalMemoryIsSet(false);
    this.totalMemory = 0;
    setUsedMemoryIsSet(false);
    this.usedMemory = 0;
  }

  public int getCpuCount() {
    return this.cpuCount;
  }

  public StatInfo setCpuCount(int cpuCount) {
    this.cpuCount = cpuCount;
    setCpuCountIsSet(true);
    return this;
  }

  public void unsetCpuCount() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CPUCOUNT_ISSET_ID);
  }

  /** Returns true if field cpuCount is set (has been assigned a value) and false otherwise */
  public boolean isSetCpuCount() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CPUCOUNT_ISSET_ID);
  }

  public void setCpuCountIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CPUCOUNT_ISSET_ID, value);
  }

  public double getCpuLoad() {
    return this.cpuLoad;
  }

  public StatInfo setCpuLoad(double cpuLoad) {
    this.cpuLoad = cpuLoad;
    setCpuLoadIsSet(true);
    return this;
  }

  public void unsetCpuLoad() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CPULOAD_ISSET_ID);
  }

  /** Returns true if field cpuLoad is set (has been assigned a value) and false otherwise */
  public boolean isSetCpuLoad() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CPULOAD_ISSET_ID);
  }

  public void setCpuLoadIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CPULOAD_ISSET_ID, value);
  }

  public long getTotalMemory() {
    return this.totalMemory;
  }

  public StatInfo setTotalMemory(long totalMemory) {
    this.totalMemory = totalMemory;
    setTotalMemoryIsSet(true);
    return this;
  }

  public void unsetTotalMemory() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TOTALMEMORY_ISSET_ID);
  }

  /** Returns true if field totalMemory is set (has been assigned a value) and false otherwise */
  public boolean isSetTotalMemory() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TOTALMEMORY_ISSET_ID);
  }

  public void setTotalMemoryIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TOTALMEMORY_ISSET_ID, value);
  }

  public long getUsedMemory() {
    return this.usedMemory;
  }

  public StatInfo setUsedMemory(long usedMemory) {
    this.usedMemory = usedMemory;
    setUsedMemoryIsSet(true);
    return this;
  }

  public void unsetUsedMemory() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __USEDMEMORY_ISSET_ID);
  }

  /** Returns true if field usedMemory is set (has been assigned a value) and false otherwise */
  public boolean isSetUsedMemory() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __USEDMEMORY_ISSET_ID);
  }

  public void setUsedMemoryIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __USEDMEMORY_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case CPU_COUNT:
      if (value == null) {
        unsetCpuCount();
      } else {
        setCpuCount((Integer)value);
      }
      break;

    case CPU_LOAD:
      if (value == null) {
        unsetCpuLoad();
      } else {
        setCpuLoad((Double)value);
      }
      break;

    case TOTAL_MEMORY:
      if (value == null) {
        unsetTotalMemory();
      } else {
        setTotalMemory((Long)value);
      }
      break;

    case USED_MEMORY:
      if (value == null) {
        unsetUsedMemory();
      } else {
        setUsedMemory((Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CPU_COUNT:
      return getCpuCount();

    case CPU_LOAD:
      return getCpuLoad();

    case TOTAL_MEMORY:
      return getTotalMemory();

    case USED_MEMORY:
      return getUsedMemory();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CPU_COUNT:
      return isSetCpuCount();
    case CPU_LOAD:
      return isSetCpuLoad();
    case TOTAL_MEMORY:
      return isSetTotalMemory();
    case USED_MEMORY:
      return isSetUsedMemory();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof StatInfo)
      return this.equals((StatInfo)that);
    return false;
  }

  public boolean equals(StatInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_cpuCount = true;
    boolean that_present_cpuCount = true;
    if (this_present_cpuCount || that_present_cpuCount) {
      if (!(this_present_cpuCount && that_present_cpuCount))
        return false;
      if (this.cpuCount != that.cpuCount)
        return false;
    }

    boolean this_present_cpuLoad = true;
    boolean that_present_cpuLoad = true;
    if (this_present_cpuLoad || that_present_cpuLoad) {
      if (!(this_present_cpuLoad && that_present_cpuLoad))
        return false;
      if (this.cpuLoad != that.cpuLoad)
        return false;
    }

    boolean this_present_totalMemory = true;
    boolean that_present_totalMemory = true;
    if (this_present_totalMemory || that_present_totalMemory) {
      if (!(this_present_totalMemory && that_present_totalMemory))
        return false;
      if (this.totalMemory != that.totalMemory)
        return false;
    }

    boolean this_present_usedMemory = true;
    boolean that_present_usedMemory = true;
    if (this_present_usedMemory || that_present_usedMemory) {
      if (!(this_present_usedMemory && that_present_usedMemory))
        return false;
      if (this.usedMemory != that.usedMemory)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + cpuCount;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(cpuLoad);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(totalMemory);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(usedMemory);

    return hashCode;
  }

  @Override
  public int compareTo(StatInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetCpuCount(), other.isSetCpuCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCpuCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cpuCount, other.cpuCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetCpuLoad(), other.isSetCpuLoad());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCpuLoad()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cpuLoad, other.cpuLoad);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetTotalMemory(), other.isSetTotalMemory());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotalMemory()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.totalMemory, other.totalMemory);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetUsedMemory(), other.isSetUsedMemory());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsedMemory()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usedMemory, other.usedMemory);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("StatInfo(");
    boolean first = true;

    sb.append("cpuCount:");
    sb.append(this.cpuCount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("cpuLoad:");
    sb.append(this.cpuLoad);
    first = false;
    if (!first) sb.append(", ");
    sb.append("totalMemory:");
    sb.append(this.totalMemory);
    first = false;
    if (!first) sb.append(", ");
    sb.append("usedMemory:");
    sb.append(this.usedMemory);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'cpuCount' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'cpuLoad' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'totalMemory' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'usedMemory' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StatInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public StatInfoStandardScheme getScheme() {
      return new StatInfoStandardScheme();
    }
  }

  private static class StatInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<StatInfo> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, StatInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CPU_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.cpuCount = iprot.readI32();
              struct.setCpuCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CPU_LOAD
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.cpuLoad = iprot.readDouble();
              struct.setCpuLoadIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TOTAL_MEMORY
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.totalMemory = iprot.readI64();
              struct.setTotalMemoryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // USED_MEMORY
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.usedMemory = iprot.readI64();
              struct.setUsedMemoryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetCpuCount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'cpuCount' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetCpuLoad()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'cpuLoad' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTotalMemory()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'totalMemory' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetUsedMemory()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'usedMemory' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, StatInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(CPU_COUNT_FIELD_DESC);
      oprot.writeI32(struct.cpuCount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CPU_LOAD_FIELD_DESC);
      oprot.writeDouble(struct.cpuLoad);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TOTAL_MEMORY_FIELD_DESC);
      oprot.writeI64(struct.totalMemory);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(USED_MEMORY_FIELD_DESC);
      oprot.writeI64(struct.usedMemory);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StatInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public StatInfoTupleScheme getScheme() {
      return new StatInfoTupleScheme();
    }
  }

  private static class StatInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<StatInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, StatInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI32(struct.cpuCount);
      oprot.writeDouble(struct.cpuLoad);
      oprot.writeI64(struct.totalMemory);
      oprot.writeI64(struct.usedMemory);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, StatInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.cpuCount = iprot.readI32();
      struct.setCpuCountIsSet(true);
      struct.cpuLoad = iprot.readDouble();
      struct.setCpuLoadIsSet(true);
      struct.totalMemory = iprot.readI64();
      struct.setTotalMemoryIsSet(true);
      struct.usedMemory = iprot.readI64();
      struct.setUsedMemoryIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

