/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.enviroment.remoteAgent.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class WebSocketData implements org.apache.thrift.TBase<WebSocketData, WebSocketData._Fields>, java.io.Serializable, Cloneable, Comparable<WebSocketData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("WebSocketData");

  private static final org.apache.thrift.protocol.TField MESSAGES_FIELD_DESC = new org.apache.thrift.protocol.TField("messages", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField CONNECTED_FIELD_DESC = new org.apache.thrift.protocol.TField("connected", org.apache.thrift.protocol.TType.BOOL, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new WebSocketDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new WebSocketDataTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.List<WebSocketMessage> messages; // required
  public boolean connected; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGES((short)1, "messages"),
    CONNECTED((short)2, "connected");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGES
          return MESSAGES;
        case 2: // CONNECTED
          return CONNECTED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __CONNECTED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGES, new org.apache.thrift.meta_data.FieldMetaData("messages", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST,
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, WebSocketMessage.class))));
    tmpMap.put(_Fields.CONNECTED, new org.apache.thrift.meta_data.FieldMetaData("connected", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(WebSocketData.class, metaDataMap);
  }

  public WebSocketData() {
  }

  public WebSocketData(
    java.util.List<WebSocketMessage> messages,
    boolean connected)
  {
    this();
    this.messages = messages;
    this.connected = connected;
    setConnectedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public WebSocketData(WebSocketData other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMessages()) {
      java.util.List<WebSocketMessage> __this__messages = new java.util.ArrayList<WebSocketMessage>(other.messages.size());
      for (WebSocketMessage other_element : other.messages) {
        __this__messages.add(new WebSocketMessage(other_element));
      }
      this.messages = __this__messages;
    }
    this.connected = other.connected;
  }

  @Override
  public WebSocketData deepCopy() {
    return new WebSocketData(this);
  }

  @Override
  public void clear() {
    this.messages = null;
    setConnectedIsSet(false);
    this.connected = false;
  }

  public int getMessagesSize() {
    return (this.messages == null) ? 0 : this.messages.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<WebSocketMessage> getMessagesIterator() {
    return (this.messages == null) ? null : this.messages.iterator();
  }

  public void addToMessages(WebSocketMessage elem) {
    if (this.messages == null) {
      this.messages = new java.util.ArrayList<WebSocketMessage>();
    }
    this.messages.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<WebSocketMessage> getMessages() {
    return this.messages;
  }

  public WebSocketData setMessages(@org.apache.thrift.annotation.Nullable java.util.List<WebSocketMessage> messages) {
    this.messages = messages;
    return this;
  }

  public void unsetMessages() {
    this.messages = null;
  }

  /** Returns true if field messages is set (has been assigned a value) and false otherwise */
  public boolean isSetMessages() {
    return this.messages != null;
  }

  public void setMessagesIsSet(boolean value) {
    if (!value) {
      this.messages = null;
    }
  }

  public boolean isConnected() {
    return this.connected;
  }

  public WebSocketData setConnected(boolean connected) {
    this.connected = connected;
    setConnectedIsSet(true);
    return this;
  }

  public void unsetConnected() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CONNECTED_ISSET_ID);
  }

  /** Returns true if field connected is set (has been assigned a value) and false otherwise */
  public boolean isSetConnected() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CONNECTED_ISSET_ID);
  }

  public void setConnectedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CONNECTED_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case MESSAGES:
      if (value == null) {
        unsetMessages();
      } else {
        setMessages((java.util.List<WebSocketMessage>)value);
      }
      break;

    case CONNECTED:
      if (value == null) {
        unsetConnected();
      } else {
        setConnected((Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGES:
      return getMessages();

    case CONNECTED:
      return isConnected();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MESSAGES:
      return isSetMessages();
    case CONNECTED:
      return isSetConnected();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof WebSocketData)
      return this.equals((WebSocketData)that);
    return false;
  }

  public boolean equals(WebSocketData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_messages = true && this.isSetMessages();
    boolean that_present_messages = true && that.isSetMessages();
    if (this_present_messages || that_present_messages) {
      if (!(this_present_messages && that_present_messages))
        return false;
      if (!this.messages.equals(that.messages))
        return false;
    }

    boolean this_present_connected = true;
    boolean that_present_connected = true;
    if (this_present_connected || that_present_connected) {
      if (!(this_present_connected && that_present_connected))
        return false;
      if (this.connected != that.connected)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMessages()) ? 131071 : 524287);
    if (isSetMessages())
      hashCode = hashCode * 8191 + messages.hashCode();

    hashCode = hashCode * 8191 + ((connected) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(WebSocketData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetMessages(), other.isSetMessages());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessages()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.messages, other.messages);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetConnected(), other.isSetConnected());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetConnected()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.connected, other.connected);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("WebSocketData(");
    boolean first = true;

    sb.append("messages:");
    if (this.messages == null) {
      sb.append("null");
    } else {
      sb.append(this.messages);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("connected:");
    sb.append(this.connected);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (messages == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'messages' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'connected' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class WebSocketDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public WebSocketDataStandardScheme getScheme() {
      return new WebSocketDataStandardScheme();
    }
  }

  private static class WebSocketDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<WebSocketData> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, WebSocketData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list28 = iprot.readListBegin();
                struct.messages = new java.util.ArrayList<WebSocketMessage>(_list28.size);
                @org.apache.thrift.annotation.Nullable WebSocketMessage _elem29;
                for (int _i30 = 0; _i30 < _list28.size; ++_i30)
                {
                  _elem29 = new WebSocketMessage();
                  _elem29.read(iprot);
                  struct.messages.add(_elem29);
                }
                iprot.readListEnd();
              }
              struct.setMessagesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CONNECTED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.connected = iprot.readBool();
              struct.setConnectedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetConnected()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'connected' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, WebSocketData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.messages != null) {
        oprot.writeFieldBegin(MESSAGES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.messages.size()));
          for (WebSocketMessage _iter31 : struct.messages)
          {
            _iter31.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(CONNECTED_FIELD_DESC);
      oprot.writeBool(struct.connected);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class WebSocketDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public WebSocketDataTupleScheme getScheme() {
      return new WebSocketDataTupleScheme();
    }
  }

  private static class WebSocketDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<WebSocketData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, WebSocketData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      {
        oprot.writeI32(struct.messages.size());
        for (WebSocketMessage _iter32 : struct.messages)
        {
          _iter32.write(oprot);
        }
      }
      oprot.writeBool(struct.connected);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, WebSocketData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list33 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
        struct.messages = new java.util.ArrayList<WebSocketMessage>(_list33.size);
        @org.apache.thrift.annotation.Nullable WebSocketMessage _elem34;
        for (int _i35 = 0; _i35 < _list33.size; ++_i35)
        {
          _elem34 = new WebSocketMessage();
          _elem34.read(iprot);
          struct.messages.add(_elem34);
        }
      }
      struct.setMessagesIsSet(true);
      struct.connected = iprot.readBool();
      struct.setConnectedIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

