/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.enviroment.remoteAgent.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class WebSocketMessage implements org.apache.thrift.TBase<WebSocketMessage, WebSocketMessage._Fields>, java.io.Serializable, Cloneable, Comparable<WebSocketMessage> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("WebSocketMessage");

  private static final org.apache.thrift.protocol.TField BINARY_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("binaryData", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TEXT_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("textData", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new WebSocketMessageStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new WebSocketMessageTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer binaryData; // optional
  public @org.apache.thrift.annotation.Nullable String textData; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BINARY_DATA((short)1, "binaryData"),
    TEXT_DATA((short)2, "textData");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BINARY_DATA
          return BINARY_DATA;
        case 2: // TEXT_DATA
          return TEXT_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields[] optionals = {_Fields.BINARY_DATA, _Fields.TEXT_DATA};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BINARY_DATA, new org.apache.thrift.meta_data.FieldMetaData("binaryData", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    tmpMap.put(_Fields.TEXT_DATA, new org.apache.thrift.meta_data.FieldMetaData("textData", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(WebSocketMessage.class, metaDataMap);
  }

  public WebSocketMessage() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public WebSocketMessage(WebSocketMessage other) {
    if (other.isSetBinaryData()) {
      this.binaryData = org.apache.thrift.TBaseHelper.copyBinary(other.binaryData);
    }
    if (other.isSetTextData()) {
      this.textData = other.textData;
    }
  }

  @Override
  public WebSocketMessage deepCopy() {
    return new WebSocketMessage(this);
  }

  @Override
  public void clear() {
    this.binaryData = null;
    this.textData = null;
  }

  public byte[] getBinaryData() {
    setBinaryData(org.apache.thrift.TBaseHelper.rightSize(binaryData));
    return binaryData == null ? null : binaryData.array();
  }

  public java.nio.ByteBuffer bufferForBinaryData() {
    return org.apache.thrift.TBaseHelper.copyBinary(binaryData);
  }

  public WebSocketMessage setBinaryData(byte[] binaryData) {
    this.binaryData = binaryData == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(binaryData.clone());
    return this;
  }

  public WebSocketMessage setBinaryData(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer binaryData) {
    this.binaryData = org.apache.thrift.TBaseHelper.copyBinary(binaryData);
    return this;
  }

  public void unsetBinaryData() {
    this.binaryData = null;
  }

  /** Returns true if field binaryData is set (has been assigned a value) and false otherwise */
  public boolean isSetBinaryData() {
    return this.binaryData != null;
  }

  public void setBinaryDataIsSet(boolean value) {
    if (!value) {
      this.binaryData = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public String getTextData() {
    return this.textData;
  }

  public WebSocketMessage setTextData(@org.apache.thrift.annotation.Nullable String textData) {
    this.textData = textData;
    return this;
  }

  public void unsetTextData() {
    this.textData = null;
  }

  /** Returns true if field textData is set (has been assigned a value) and false otherwise */
  public boolean isSetTextData() {
    return this.textData != null;
  }

  public void setTextDataIsSet(boolean value) {
    if (!value) {
      this.textData = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case BINARY_DATA:
      if (value == null) {
        unsetBinaryData();
      } else {
        if (value instanceof byte[]) {
          setBinaryData((byte[])value);
        } else {
          setBinaryData((java.nio.ByteBuffer)value);
        }
      }
      break;

    case TEXT_DATA:
      if (value == null) {
        unsetTextData();
      } else {
        setTextData((String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BINARY_DATA:
      return getBinaryData();

    case TEXT_DATA:
      return getTextData();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BINARY_DATA:
      return isSetBinaryData();
    case TEXT_DATA:
      return isSetTextData();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof WebSocketMessage)
      return this.equals((WebSocketMessage)that);
    return false;
  }

  public boolean equals(WebSocketMessage that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_binaryData = true && this.isSetBinaryData();
    boolean that_present_binaryData = true && that.isSetBinaryData();
    if (this_present_binaryData || that_present_binaryData) {
      if (!(this_present_binaryData && that_present_binaryData))
        return false;
      if (!this.binaryData.equals(that.binaryData))
        return false;
    }

    boolean this_present_textData = true && this.isSetTextData();
    boolean that_present_textData = true && that.isSetTextData();
    if (this_present_textData || that_present_textData) {
      if (!(this_present_textData && that_present_textData))
        return false;
      if (!this.textData.equals(that.textData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetBinaryData()) ? 131071 : 524287);
    if (isSetBinaryData())
      hashCode = hashCode * 8191 + binaryData.hashCode();

    hashCode = hashCode * 8191 + ((isSetTextData()) ? 131071 : 524287);
    if (isSetTextData())
      hashCode = hashCode * 8191 + textData.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(WebSocketMessage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetBinaryData(), other.isSetBinaryData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBinaryData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.binaryData, other.binaryData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetTextData(), other.isSetTextData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTextData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.textData, other.textData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("WebSocketMessage(");
    boolean first = true;

    if (isSetBinaryData()) {
      sb.append("binaryData:");
      if (this.binaryData == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.binaryData, sb);
      }
      first = false;
    }
    if (isSetTextData()) {
      if (!first) sb.append(", ");
      sb.append("textData:");
      if (this.textData == null) {
        sb.append("null");
      } else {
        sb.append(this.textData);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class WebSocketMessageStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public WebSocketMessageStandardScheme getScheme() {
      return new WebSocketMessageStandardScheme();
    }
  }

  private static class WebSocketMessageStandardScheme extends org.apache.thrift.scheme.StandardScheme<WebSocketMessage> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, WebSocketMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BINARY_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.binaryData = iprot.readBinary();
              struct.setBinaryDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TEXT_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.textData = iprot.readString();
              struct.setTextDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, WebSocketMessage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.binaryData != null) {
        if (struct.isSetBinaryData()) {
          oprot.writeFieldBegin(BINARY_DATA_FIELD_DESC);
          oprot.writeBinary(struct.binaryData);
          oprot.writeFieldEnd();
        }
      }
      if (struct.textData != null) {
        if (struct.isSetTextData()) {
          oprot.writeFieldBegin(TEXT_DATA_FIELD_DESC);
          oprot.writeString(struct.textData);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class WebSocketMessageTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public WebSocketMessageTupleScheme getScheme() {
      return new WebSocketMessageTupleScheme();
    }
  }

  private static class WebSocketMessageTupleScheme extends org.apache.thrift.scheme.TupleScheme<WebSocketMessage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, WebSocketMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetBinaryData()) {
        optionals.set(0);
      }
      if (struct.isSetTextData()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetBinaryData()) {
        oprot.writeBinary(struct.binaryData);
      }
      if (struct.isSetTextData()) {
        oprot.writeString(struct.textData);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, WebSocketMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.binaryData = iprot.readBinary();
        struct.setBinaryDataIsSet(true);
      }
      if (incoming.get(1)) {
        struct.textData = iprot.readString();
        struct.setTextDataIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

