/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.externalSystem.shared;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ExternalConstants {

  public static final java.lang.String SOURCE_FLAG_PRODUCTION = "prod";

  public static final java.lang.String SOURCE_FLAG_TEST = "test";

  public static final java.lang.String SOURCE_FLAG_RESOURCE = "res";

  public static final java.lang.String SOURCE_FLAG_EXCLUDED = "excluded";

  public static final ExternalSourceType PRODUCTION = new ExternalSourceType();
  static {
    java.util.Set<java.lang.String> tmp72 = new java.util.HashSet<java.lang.String>();
    tmp72.add("prod");

    PRODUCTION.setFlags(tmp72);
    PRODUCTION.setName("PRODUCTION");
  }

  public static final ExternalSourceType PRODUCTION_RESOURCE = new ExternalSourceType();
  static {
    java.util.Set<java.lang.String> tmp73 = new java.util.HashSet<java.lang.String>();
    tmp73.add("prod");
    tmp73.add("res");

    PRODUCTION_RESOURCE.setFlags(tmp73);
    PRODUCTION_RESOURCE.setName("PRODUCTION_RESOURCE");
  }

  public static final ExternalSourceType TEST = new ExternalSourceType();
  static {
    java.util.Set<java.lang.String> tmp74 = new java.util.HashSet<java.lang.String>();
    tmp74.add("test");

    TEST.setFlags(tmp74);
    TEST.setName("TEST");
  }

  public static final ExternalSourceType TEST_RESOURCE = new ExternalSourceType();
  static {
    java.util.Set<java.lang.String> tmp75 = new java.util.HashSet<java.lang.String>();
    tmp75.add("test");
    tmp75.add("res");

    TEST_RESOURCE.setFlags(tmp75);
    TEST_RESOURCE.setName("TEST_RESOURCE");
  }

  public static final ExternalSourceType EXCLUDED = new ExternalSourceType();
  static {
    java.util.Set<java.lang.String> tmp76 = new java.util.HashSet<java.lang.String>();
    tmp76.add("excluded");

    EXCLUDED.setFlags(tmp76);
    EXCLUDED.setName("EXCLUDED");
  }

}
