/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.externalSystem.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ThriftDataNode implements org.apache.thrift.TBase<ThriftDataNode, ThriftDataNode._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftDataNode> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftDataNode");

  private static final org.apache.thrift.protocol.TField KEY_FIELD_DESC = new org.apache.thrift.protocol.TField("key", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField CHILDREN_FIELD_DESC = new org.apache.thrift.protocol.TField("children", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField PROJECT_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("projectData", org.apache.thrift.protocol.TType.STRUCT, (short)10);
  private static final org.apache.thrift.protocol.TField MODULE_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("moduleData", org.apache.thrift.protocol.TType.STRUCT, (short)11);
  private static final org.apache.thrift.protocol.TField LIBRARY_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("libraryData", org.apache.thrift.protocol.TType.STRUCT, (short)12);
  private static final org.apache.thrift.protocol.TField CONTENT_ROOT_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("contentRootData", org.apache.thrift.protocol.TType.STRUCT, (short)13);
  private static final org.apache.thrift.protocol.TField MODULE_DEPENDENCY_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("moduleDependencyData", org.apache.thrift.protocol.TType.STRUCT, (short)14);
  private static final org.apache.thrift.protocol.TField LIBRARY_DEPENDENCY_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("libraryDependencyData", org.apache.thrift.protocol.TType.STRUCT, (short)15);
  private static final org.apache.thrift.protocol.TField TASK_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("taskData", org.apache.thrift.protocol.TType.STRUCT, (short)16);
  private static final org.apache.thrift.protocol.TField EXTENSION_DATA_FIELD_DESC = new org.apache.thrift.protocol.TField("extensionData", org.apache.thrift.protocol.TType.STRING, (short)20);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftDataNodeStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftDataNodeTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String key; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<ThriftDataNode> children; // required
  public @org.apache.thrift.annotation.Nullable ThriftProjectData projectData; // optional
  public @org.apache.thrift.annotation.Nullable ThriftModuleData moduleData; // optional
  public @org.apache.thrift.annotation.Nullable ThriftLibraryData libraryData; // optional
  public @org.apache.thrift.annotation.Nullable ThriftContentRootData contentRootData; // optional
  public @org.apache.thrift.annotation.Nullable ThriftModuleDependencyData moduleDependencyData; // optional
  public @org.apache.thrift.annotation.Nullable ThriftLibraryDependencyData libraryDependencyData; // optional
  public @org.apache.thrift.annotation.Nullable ThriftTaskData taskData; // optional
  public @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer extensionData; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    KEY((short)1, "key"),
    CHILDREN((short)2, "children"),
    PROJECT_DATA((short)10, "projectData"),
    MODULE_DATA((short)11, "moduleData"),
    LIBRARY_DATA((short)12, "libraryData"),
    CONTENT_ROOT_DATA((short)13, "contentRootData"),
    MODULE_DEPENDENCY_DATA((short)14, "moduleDependencyData"),
    LIBRARY_DEPENDENCY_DATA((short)15, "libraryDependencyData"),
    TASK_DATA((short)16, "taskData"),
    EXTENSION_DATA((short)20, "extensionData");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // KEY
          return KEY;
        case 2: // CHILDREN
          return CHILDREN;
        case 10: // PROJECT_DATA
          return PROJECT_DATA;
        case 11: // MODULE_DATA
          return MODULE_DATA;
        case 12: // LIBRARY_DATA
          return LIBRARY_DATA;
        case 13: // CONTENT_ROOT_DATA
          return CONTENT_ROOT_DATA;
        case 14: // MODULE_DEPENDENCY_DATA
          return MODULE_DEPENDENCY_DATA;
        case 15: // LIBRARY_DEPENDENCY_DATA
          return LIBRARY_DEPENDENCY_DATA;
        case 16: // TASK_DATA
          return TASK_DATA;
        case 20: // EXTENSION_DATA
          return EXTENSION_DATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.PROJECT_DATA,_Fields.MODULE_DATA,_Fields.LIBRARY_DATA,_Fields.CONTENT_ROOT_DATA,_Fields.MODULE_DEPENDENCY_DATA,_Fields.LIBRARY_DEPENDENCY_DATA,_Fields.TASK_DATA,_Fields.EXTENSION_DATA};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.KEY, new org.apache.thrift.meta_data.FieldMetaData("key", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CHILDREN, new org.apache.thrift.meta_data.FieldMetaData("children", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftDataNode.class))));
    tmpMap.put(_Fields.PROJECT_DATA, new org.apache.thrift.meta_data.FieldMetaData("projectData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftProjectData.class)));
    tmpMap.put(_Fields.MODULE_DATA, new org.apache.thrift.meta_data.FieldMetaData("moduleData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftModuleData.class)));
    tmpMap.put(_Fields.LIBRARY_DATA, new org.apache.thrift.meta_data.FieldMetaData("libraryData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftLibraryData.class)));
    tmpMap.put(_Fields.CONTENT_ROOT_DATA, new org.apache.thrift.meta_data.FieldMetaData("contentRootData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftContentRootData.class)));
    tmpMap.put(_Fields.MODULE_DEPENDENCY_DATA, new org.apache.thrift.meta_data.FieldMetaData("moduleDependencyData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftModuleDependencyData.class)));
    tmpMap.put(_Fields.LIBRARY_DEPENDENCY_DATA, new org.apache.thrift.meta_data.FieldMetaData("libraryDependencyData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftLibraryDependencyData.class)));
    tmpMap.put(_Fields.TASK_DATA, new org.apache.thrift.meta_data.FieldMetaData("taskData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftTaskData.class)));
    tmpMap.put(_Fields.EXTENSION_DATA, new org.apache.thrift.meta_data.FieldMetaData("extensionData", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING        , true)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftDataNode.class, metaDataMap);
  }

  public ThriftDataNode() {
  }

  public ThriftDataNode(
    java.lang.String key,
    java.util.List<ThriftDataNode> children)
  {
    this();
    this.key = key;
    this.children = children;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftDataNode(ThriftDataNode other) {
    if (other.isSetKey()) {
      this.key = other.key;
    }
    if (other.isSetChildren()) {
      java.util.List<ThriftDataNode> __this__children = new java.util.ArrayList<ThriftDataNode>(other.children.size());
      for (ThriftDataNode other_element : other.children) {
        __this__children.add(new ThriftDataNode(other_element));
      }
      this.children = __this__children;
    }
    if (other.isSetProjectData()) {
      this.projectData = new ThriftProjectData(other.projectData);
    }
    if (other.isSetModuleData()) {
      this.moduleData = new ThriftModuleData(other.moduleData);
    }
    if (other.isSetLibraryData()) {
      this.libraryData = new ThriftLibraryData(other.libraryData);
    }
    if (other.isSetContentRootData()) {
      this.contentRootData = new ThriftContentRootData(other.contentRootData);
    }
    if (other.isSetModuleDependencyData()) {
      this.moduleDependencyData = new ThriftModuleDependencyData(other.moduleDependencyData);
    }
    if (other.isSetLibraryDependencyData()) {
      this.libraryDependencyData = new ThriftLibraryDependencyData(other.libraryDependencyData);
    }
    if (other.isSetTaskData()) {
      this.taskData = new ThriftTaskData(other.taskData);
    }
    if (other.isSetExtensionData()) {
      this.extensionData = org.apache.thrift.TBaseHelper.copyBinary(other.extensionData);
    }
  }

  @Override
  public ThriftDataNode deepCopy() {
    return new ThriftDataNode(this);
  }

  @Override
  public void clear() {
    this.key = null;
    this.children = null;
    this.projectData = null;
    this.moduleData = null;
    this.libraryData = null;
    this.contentRootData = null;
    this.moduleDependencyData = null;
    this.libraryDependencyData = null;
    this.taskData = null;
    this.extensionData = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getKey() {
    return this.key;
  }

  public ThriftDataNode setKey(@org.apache.thrift.annotation.Nullable java.lang.String key) {
    this.key = key;
    return this;
  }

  public void unsetKey() {
    this.key = null;
  }

  /** Returns true if field key is set (has been assigned a value) and false otherwise */
  public boolean isSetKey() {
    return this.key != null;
  }

  public void setKeyIsSet(boolean value) {
    if (!value) {
      this.key = null;
    }
  }

  public int getChildrenSize() {
    return (this.children == null) ? 0 : this.children.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<ThriftDataNode> getChildrenIterator() {
    return (this.children == null) ? null : this.children.iterator();
  }

  public void addToChildren(ThriftDataNode elem) {
    if (this.children == null) {
      this.children = new java.util.ArrayList<ThriftDataNode>();
    }
    this.children.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<ThriftDataNode> getChildren() {
    return this.children;
  }

  public ThriftDataNode setChildren(@org.apache.thrift.annotation.Nullable java.util.List<ThriftDataNode> children) {
    this.children = children;
    return this;
  }

  public void unsetChildren() {
    this.children = null;
  }

  /** Returns true if field children is set (has been assigned a value) and false otherwise */
  public boolean isSetChildren() {
    return this.children != null;
  }

  public void setChildrenIsSet(boolean value) {
    if (!value) {
      this.children = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftProjectData getProjectData() {
    return this.projectData;
  }

  public ThriftDataNode setProjectData(@org.apache.thrift.annotation.Nullable ThriftProjectData projectData) {
    this.projectData = projectData;
    return this;
  }

  public void unsetProjectData() {
    this.projectData = null;
  }

  /** Returns true if field projectData is set (has been assigned a value) and false otherwise */
  public boolean isSetProjectData() {
    return this.projectData != null;
  }

  public void setProjectDataIsSet(boolean value) {
    if (!value) {
      this.projectData = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftModuleData getModuleData() {
    return this.moduleData;
  }

  public ThriftDataNode setModuleData(@org.apache.thrift.annotation.Nullable ThriftModuleData moduleData) {
    this.moduleData = moduleData;
    return this;
  }

  public void unsetModuleData() {
    this.moduleData = null;
  }

  /** Returns true if field moduleData is set (has been assigned a value) and false otherwise */
  public boolean isSetModuleData() {
    return this.moduleData != null;
  }

  public void setModuleDataIsSet(boolean value) {
    if (!value) {
      this.moduleData = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftLibraryData getLibraryData() {
    return this.libraryData;
  }

  public ThriftDataNode setLibraryData(@org.apache.thrift.annotation.Nullable ThriftLibraryData libraryData) {
    this.libraryData = libraryData;
    return this;
  }

  public void unsetLibraryData() {
    this.libraryData = null;
  }

  /** Returns true if field libraryData is set (has been assigned a value) and false otherwise */
  public boolean isSetLibraryData() {
    return this.libraryData != null;
  }

  public void setLibraryDataIsSet(boolean value) {
    if (!value) {
      this.libraryData = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftContentRootData getContentRootData() {
    return this.contentRootData;
  }

  public ThriftDataNode setContentRootData(@org.apache.thrift.annotation.Nullable ThriftContentRootData contentRootData) {
    this.contentRootData = contentRootData;
    return this;
  }

  public void unsetContentRootData() {
    this.contentRootData = null;
  }

  /** Returns true if field contentRootData is set (has been assigned a value) and false otherwise */
  public boolean isSetContentRootData() {
    return this.contentRootData != null;
  }

  public void setContentRootDataIsSet(boolean value) {
    if (!value) {
      this.contentRootData = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftModuleDependencyData getModuleDependencyData() {
    return this.moduleDependencyData;
  }

  public ThriftDataNode setModuleDependencyData(@org.apache.thrift.annotation.Nullable ThriftModuleDependencyData moduleDependencyData) {
    this.moduleDependencyData = moduleDependencyData;
    return this;
  }

  public void unsetModuleDependencyData() {
    this.moduleDependencyData = null;
  }

  /** Returns true if field moduleDependencyData is set (has been assigned a value) and false otherwise */
  public boolean isSetModuleDependencyData() {
    return this.moduleDependencyData != null;
  }

  public void setModuleDependencyDataIsSet(boolean value) {
    if (!value) {
      this.moduleDependencyData = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftLibraryDependencyData getLibraryDependencyData() {
    return this.libraryDependencyData;
  }

  public ThriftDataNode setLibraryDependencyData(@org.apache.thrift.annotation.Nullable ThriftLibraryDependencyData libraryDependencyData) {
    this.libraryDependencyData = libraryDependencyData;
    return this;
  }

  public void unsetLibraryDependencyData() {
    this.libraryDependencyData = null;
  }

  /** Returns true if field libraryDependencyData is set (has been assigned a value) and false otherwise */
  public boolean isSetLibraryDependencyData() {
    return this.libraryDependencyData != null;
  }

  public void setLibraryDependencyDataIsSet(boolean value) {
    if (!value) {
      this.libraryDependencyData = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftTaskData getTaskData() {
    return this.taskData;
  }

  public ThriftDataNode setTaskData(@org.apache.thrift.annotation.Nullable ThriftTaskData taskData) {
    this.taskData = taskData;
    return this;
  }

  public void unsetTaskData() {
    this.taskData = null;
  }

  /** Returns true if field taskData is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskData() {
    return this.taskData != null;
  }

  public void setTaskDataIsSet(boolean value) {
    if (!value) {
      this.taskData = null;
    }
  }

  public byte[] getExtensionData() {
    setExtensionData(org.apache.thrift.TBaseHelper.rightSize(extensionData));
    return extensionData == null ? null : extensionData.array();
  }

  public java.nio.ByteBuffer bufferForExtensionData() {
    return org.apache.thrift.TBaseHelper.copyBinary(extensionData);
  }

  public ThriftDataNode setExtensionData(byte[] extensionData) {
    this.extensionData = extensionData == null ? (java.nio.ByteBuffer)null   : java.nio.ByteBuffer.wrap(extensionData.clone());
    return this;
  }

  public ThriftDataNode setExtensionData(@org.apache.thrift.annotation.Nullable java.nio.ByteBuffer extensionData) {
    this.extensionData = org.apache.thrift.TBaseHelper.copyBinary(extensionData);
    return this;
  }

  public void unsetExtensionData() {
    this.extensionData = null;
  }

  /** Returns true if field extensionData is set (has been assigned a value) and false otherwise */
  public boolean isSetExtensionData() {
    return this.extensionData != null;
  }

  public void setExtensionDataIsSet(boolean value) {
    if (!value) {
      this.extensionData = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case KEY:
      if (value == null) {
        unsetKey();
      } else {
        setKey((java.lang.String)value);
      }
      break;

    case CHILDREN:
      if (value == null) {
        unsetChildren();
      } else {
        setChildren((java.util.List<ThriftDataNode>)value);
      }
      break;

    case PROJECT_DATA:
      if (value == null) {
        unsetProjectData();
      } else {
        setProjectData((ThriftProjectData)value);
      }
      break;

    case MODULE_DATA:
      if (value == null) {
        unsetModuleData();
      } else {
        setModuleData((ThriftModuleData)value);
      }
      break;

    case LIBRARY_DATA:
      if (value == null) {
        unsetLibraryData();
      } else {
        setLibraryData((ThriftLibraryData)value);
      }
      break;

    case CONTENT_ROOT_DATA:
      if (value == null) {
        unsetContentRootData();
      } else {
        setContentRootData((ThriftContentRootData)value);
      }
      break;

    case MODULE_DEPENDENCY_DATA:
      if (value == null) {
        unsetModuleDependencyData();
      } else {
        setModuleDependencyData((ThriftModuleDependencyData)value);
      }
      break;

    case LIBRARY_DEPENDENCY_DATA:
      if (value == null) {
        unsetLibraryDependencyData();
      } else {
        setLibraryDependencyData((ThriftLibraryDependencyData)value);
      }
      break;

    case TASK_DATA:
      if (value == null) {
        unsetTaskData();
      } else {
        setTaskData((ThriftTaskData)value);
      }
      break;

    case EXTENSION_DATA:
      if (value == null) {
        unsetExtensionData();
      } else {
        if (value instanceof byte[]) {
          setExtensionData((byte[])value);
        } else {
          setExtensionData((java.nio.ByteBuffer)value);
        }
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case KEY:
      return getKey();

    case CHILDREN:
      return getChildren();

    case PROJECT_DATA:
      return getProjectData();

    case MODULE_DATA:
      return getModuleData();

    case LIBRARY_DATA:
      return getLibraryData();

    case CONTENT_ROOT_DATA:
      return getContentRootData();

    case MODULE_DEPENDENCY_DATA:
      return getModuleDependencyData();

    case LIBRARY_DEPENDENCY_DATA:
      return getLibraryDependencyData();

    case TASK_DATA:
      return getTaskData();

    case EXTENSION_DATA:
      return getExtensionData();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case KEY:
      return isSetKey();
    case CHILDREN:
      return isSetChildren();
    case PROJECT_DATA:
      return isSetProjectData();
    case MODULE_DATA:
      return isSetModuleData();
    case LIBRARY_DATA:
      return isSetLibraryData();
    case CONTENT_ROOT_DATA:
      return isSetContentRootData();
    case MODULE_DEPENDENCY_DATA:
      return isSetModuleDependencyData();
    case LIBRARY_DEPENDENCY_DATA:
      return isSetLibraryDependencyData();
    case TASK_DATA:
      return isSetTaskData();
    case EXTENSION_DATA:
      return isSetExtensionData();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ThriftDataNode)
      return this.equals((ThriftDataNode)that);
    return false;
  }

  public boolean equals(ThriftDataNode that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_key = true && this.isSetKey();
    boolean that_present_key = true && that.isSetKey();
    if (this_present_key || that_present_key) {
      if (!(this_present_key && that_present_key))
        return false;
      if (!this.key.equals(that.key))
        return false;
    }

    boolean this_present_children = true && this.isSetChildren();
    boolean that_present_children = true && that.isSetChildren();
    if (this_present_children || that_present_children) {
      if (!(this_present_children && that_present_children))
        return false;
      if (!this.children.equals(that.children))
        return false;
    }

    boolean this_present_projectData = true && this.isSetProjectData();
    boolean that_present_projectData = true && that.isSetProjectData();
    if (this_present_projectData || that_present_projectData) {
      if (!(this_present_projectData && that_present_projectData))
        return false;
      if (!this.projectData.equals(that.projectData))
        return false;
    }

    boolean this_present_moduleData = true && this.isSetModuleData();
    boolean that_present_moduleData = true && that.isSetModuleData();
    if (this_present_moduleData || that_present_moduleData) {
      if (!(this_present_moduleData && that_present_moduleData))
        return false;
      if (!this.moduleData.equals(that.moduleData))
        return false;
    }

    boolean this_present_libraryData = true && this.isSetLibraryData();
    boolean that_present_libraryData = true && that.isSetLibraryData();
    if (this_present_libraryData || that_present_libraryData) {
      if (!(this_present_libraryData && that_present_libraryData))
        return false;
      if (!this.libraryData.equals(that.libraryData))
        return false;
    }

    boolean this_present_contentRootData = true && this.isSetContentRootData();
    boolean that_present_contentRootData = true && that.isSetContentRootData();
    if (this_present_contentRootData || that_present_contentRootData) {
      if (!(this_present_contentRootData && that_present_contentRootData))
        return false;
      if (!this.contentRootData.equals(that.contentRootData))
        return false;
    }

    boolean this_present_moduleDependencyData = true && this.isSetModuleDependencyData();
    boolean that_present_moduleDependencyData = true && that.isSetModuleDependencyData();
    if (this_present_moduleDependencyData || that_present_moduleDependencyData) {
      if (!(this_present_moduleDependencyData && that_present_moduleDependencyData))
        return false;
      if (!this.moduleDependencyData.equals(that.moduleDependencyData))
        return false;
    }

    boolean this_present_libraryDependencyData = true && this.isSetLibraryDependencyData();
    boolean that_present_libraryDependencyData = true && that.isSetLibraryDependencyData();
    if (this_present_libraryDependencyData || that_present_libraryDependencyData) {
      if (!(this_present_libraryDependencyData && that_present_libraryDependencyData))
        return false;
      if (!this.libraryDependencyData.equals(that.libraryDependencyData))
        return false;
    }

    boolean this_present_taskData = true && this.isSetTaskData();
    boolean that_present_taskData = true && that.isSetTaskData();
    if (this_present_taskData || that_present_taskData) {
      if (!(this_present_taskData && that_present_taskData))
        return false;
      if (!this.taskData.equals(that.taskData))
        return false;
    }

    boolean this_present_extensionData = true && this.isSetExtensionData();
    boolean that_present_extensionData = true && that.isSetExtensionData();
    if (this_present_extensionData || that_present_extensionData) {
      if (!(this_present_extensionData && that_present_extensionData))
        return false;
      if (!this.extensionData.equals(that.extensionData))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetKey()) ? 131071 : 524287);
    if (isSetKey())
      hashCode = hashCode * 8191 + key.hashCode();

    hashCode = hashCode * 8191 + ((isSetChildren()) ? 131071 : 524287);
    if (isSetChildren())
      hashCode = hashCode * 8191 + children.hashCode();

    hashCode = hashCode * 8191 + ((isSetProjectData()) ? 131071 : 524287);
    if (isSetProjectData())
      hashCode = hashCode * 8191 + projectData.hashCode();

    hashCode = hashCode * 8191 + ((isSetModuleData()) ? 131071 : 524287);
    if (isSetModuleData())
      hashCode = hashCode * 8191 + moduleData.hashCode();

    hashCode = hashCode * 8191 + ((isSetLibraryData()) ? 131071 : 524287);
    if (isSetLibraryData())
      hashCode = hashCode * 8191 + libraryData.hashCode();

    hashCode = hashCode * 8191 + ((isSetContentRootData()) ? 131071 : 524287);
    if (isSetContentRootData())
      hashCode = hashCode * 8191 + contentRootData.hashCode();

    hashCode = hashCode * 8191 + ((isSetModuleDependencyData()) ? 131071 : 524287);
    if (isSetModuleDependencyData())
      hashCode = hashCode * 8191 + moduleDependencyData.hashCode();

    hashCode = hashCode * 8191 + ((isSetLibraryDependencyData()) ? 131071 : 524287);
    if (isSetLibraryDependencyData())
      hashCode = hashCode * 8191 + libraryDependencyData.hashCode();

    hashCode = hashCode * 8191 + ((isSetTaskData()) ? 131071 : 524287);
    if (isSetTaskData())
      hashCode = hashCode * 8191 + taskData.hashCode();

    hashCode = hashCode * 8191 + ((isSetExtensionData()) ? 131071 : 524287);
    if (isSetExtensionData())
      hashCode = hashCode * 8191 + extensionData.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ThriftDataNode other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetKey(), other.isSetKey());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKey()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.key, other.key);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetChildren(), other.isSetChildren());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChildren()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.children, other.children);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetProjectData(), other.isSetProjectData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProjectData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.projectData, other.projectData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetModuleData(), other.isSetModuleData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetModuleData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.moduleData, other.moduleData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLibraryData(), other.isSetLibraryData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLibraryData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.libraryData, other.libraryData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetContentRootData(), other.isSetContentRootData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetContentRootData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.contentRootData, other.contentRootData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetModuleDependencyData(), other.isSetModuleDependencyData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetModuleDependencyData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.moduleDependencyData, other.moduleDependencyData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLibraryDependencyData(), other.isSetLibraryDependencyData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLibraryDependencyData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.libraryDependencyData, other.libraryDependencyData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTaskData(), other.isSetTaskData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskData, other.taskData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetExtensionData(), other.isSetExtensionData());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExtensionData()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.extensionData, other.extensionData);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftDataNode(");
    boolean first = true;

    sb.append("key:");
    if (this.key == null) {
      sb.append("null");
    } else {
      sb.append(this.key);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("children:");
    if (this.children == null) {
      sb.append("null");
    } else {
      sb.append(this.children);
    }
    first = false;
    if (isSetProjectData()) {
      if (!first) sb.append(", ");
      sb.append("projectData:");
      if (this.projectData == null) {
        sb.append("null");
      } else {
        sb.append(this.projectData);
      }
      first = false;
    }
    if (isSetModuleData()) {
      if (!first) sb.append(", ");
      sb.append("moduleData:");
      if (this.moduleData == null) {
        sb.append("null");
      } else {
        sb.append(this.moduleData);
      }
      first = false;
    }
    if (isSetLibraryData()) {
      if (!first) sb.append(", ");
      sb.append("libraryData:");
      if (this.libraryData == null) {
        sb.append("null");
      } else {
        sb.append(this.libraryData);
      }
      first = false;
    }
    if (isSetContentRootData()) {
      if (!first) sb.append(", ");
      sb.append("contentRootData:");
      if (this.contentRootData == null) {
        sb.append("null");
      } else {
        sb.append(this.contentRootData);
      }
      first = false;
    }
    if (isSetModuleDependencyData()) {
      if (!first) sb.append(", ");
      sb.append("moduleDependencyData:");
      if (this.moduleDependencyData == null) {
        sb.append("null");
      } else {
        sb.append(this.moduleDependencyData);
      }
      first = false;
    }
    if (isSetLibraryDependencyData()) {
      if (!first) sb.append(", ");
      sb.append("libraryDependencyData:");
      if (this.libraryDependencyData == null) {
        sb.append("null");
      } else {
        sb.append(this.libraryDependencyData);
      }
      first = false;
    }
    if (isSetTaskData()) {
      if (!first) sb.append(", ");
      sb.append("taskData:");
      if (this.taskData == null) {
        sb.append("null");
      } else {
        sb.append(this.taskData);
      }
      first = false;
    }
    if (isSetExtensionData()) {
      if (!first) sb.append(", ");
      sb.append("extensionData:");
      if (this.extensionData == null) {
        sb.append("null");
      } else {
        org.apache.thrift.TBaseHelper.toString(this.extensionData, sb);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (key == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'key' was not present! Struct: " + toString());
    }
    if (children == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'children' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (projectData != null) {
      projectData.validate();
    }
    if (moduleData != null) {
      moduleData.validate();
    }
    if (libraryData != null) {
      libraryData.validate();
    }
    if (contentRootData != null) {
      contentRootData.validate();
    }
    if (moduleDependencyData != null) {
      moduleDependencyData.validate();
    }
    if (libraryDependencyData != null) {
      libraryDependencyData.validate();
    }
    if (taskData != null) {
      taskData.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftDataNodeStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftDataNodeStandardScheme getScheme() {
      return new ThriftDataNodeStandardScheme();
    }
  }

  private static class ThriftDataNodeStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftDataNode> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftDataNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // KEY
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.key = iprot.readString();
              struct.setKeyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CHILDREN
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list62 = iprot.readListBegin();
                struct.children = new java.util.ArrayList<ThriftDataNode>(_list62.size);
                @org.apache.thrift.annotation.Nullable ThriftDataNode _elem63;
                for (int _i64 = 0; _i64 < _list62.size; ++_i64)
                {
                  _elem63 = new ThriftDataNode();
                  _elem63.read(iprot);
                  struct.children.add(_elem63);
                }
                iprot.readListEnd();
              }
              struct.setChildrenIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // PROJECT_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.projectData = new ThriftProjectData();
              struct.projectData.read(iprot);
              struct.setProjectDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // MODULE_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.moduleData = new ThriftModuleData();
              struct.moduleData.read(iprot);
              struct.setModuleDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // LIBRARY_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.libraryData = new ThriftLibraryData();
              struct.libraryData.read(iprot);
              struct.setLibraryDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // CONTENT_ROOT_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.contentRootData = new ThriftContentRootData();
              struct.contentRootData.read(iprot);
              struct.setContentRootDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // MODULE_DEPENDENCY_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.moduleDependencyData = new ThriftModuleDependencyData();
              struct.moduleDependencyData.read(iprot);
              struct.setModuleDependencyDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // LIBRARY_DEPENDENCY_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.libraryDependencyData = new ThriftLibraryDependencyData();
              struct.libraryDependencyData.read(iprot);
              struct.setLibraryDependencyDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // TASK_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.taskData = new ThriftTaskData();
              struct.taskData.read(iprot);
              struct.setTaskDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 20: // EXTENSION_DATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.extensionData = iprot.readBinary();
              struct.setExtensionDataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftDataNode struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.key != null) {
        oprot.writeFieldBegin(KEY_FIELD_DESC);
        oprot.writeString(struct.key);
        oprot.writeFieldEnd();
      }
      if (struct.children != null) {
        oprot.writeFieldBegin(CHILDREN_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.children.size()));
          for (ThriftDataNode _iter65 : struct.children)
          {
            _iter65.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.projectData != null) {
        if (struct.isSetProjectData()) {
          oprot.writeFieldBegin(PROJECT_DATA_FIELD_DESC);
          struct.projectData.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.moduleData != null) {
        if (struct.isSetModuleData()) {
          oprot.writeFieldBegin(MODULE_DATA_FIELD_DESC);
          struct.moduleData.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.libraryData != null) {
        if (struct.isSetLibraryData()) {
          oprot.writeFieldBegin(LIBRARY_DATA_FIELD_DESC);
          struct.libraryData.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.contentRootData != null) {
        if (struct.isSetContentRootData()) {
          oprot.writeFieldBegin(CONTENT_ROOT_DATA_FIELD_DESC);
          struct.contentRootData.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.moduleDependencyData != null) {
        if (struct.isSetModuleDependencyData()) {
          oprot.writeFieldBegin(MODULE_DEPENDENCY_DATA_FIELD_DESC);
          struct.moduleDependencyData.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.libraryDependencyData != null) {
        if (struct.isSetLibraryDependencyData()) {
          oprot.writeFieldBegin(LIBRARY_DEPENDENCY_DATA_FIELD_DESC);
          struct.libraryDependencyData.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.taskData != null) {
        if (struct.isSetTaskData()) {
          oprot.writeFieldBegin(TASK_DATA_FIELD_DESC);
          struct.taskData.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.extensionData != null) {
        if (struct.isSetExtensionData()) {
          oprot.writeFieldBegin(EXTENSION_DATA_FIELD_DESC);
          oprot.writeBinary(struct.extensionData);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftDataNodeTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftDataNodeTupleScheme getScheme() {
      return new ThriftDataNodeTupleScheme();
    }
  }

  private static class ThriftDataNodeTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftDataNode> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftDataNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.key);
      {
        oprot.writeI32(struct.children.size());
        for (ThriftDataNode _iter66 : struct.children)
        {
          _iter66.write(oprot);
        }
      }
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetProjectData()) {
        optionals.set(0);
      }
      if (struct.isSetModuleData()) {
        optionals.set(1);
      }
      if (struct.isSetLibraryData()) {
        optionals.set(2);
      }
      if (struct.isSetContentRootData()) {
        optionals.set(3);
      }
      if (struct.isSetModuleDependencyData()) {
        optionals.set(4);
      }
      if (struct.isSetLibraryDependencyData()) {
        optionals.set(5);
      }
      if (struct.isSetTaskData()) {
        optionals.set(6);
      }
      if (struct.isSetExtensionData()) {
        optionals.set(7);
      }
      oprot.writeBitSet(optionals, 8);
      if (struct.isSetProjectData()) {
        struct.projectData.write(oprot);
      }
      if (struct.isSetModuleData()) {
        struct.moduleData.write(oprot);
      }
      if (struct.isSetLibraryData()) {
        struct.libraryData.write(oprot);
      }
      if (struct.isSetContentRootData()) {
        struct.contentRootData.write(oprot);
      }
      if (struct.isSetModuleDependencyData()) {
        struct.moduleDependencyData.write(oprot);
      }
      if (struct.isSetLibraryDependencyData()) {
        struct.libraryDependencyData.write(oprot);
      }
      if (struct.isSetTaskData()) {
        struct.taskData.write(oprot);
      }
      if (struct.isSetExtensionData()) {
        oprot.writeBinary(struct.extensionData);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftDataNode struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.key = iprot.readString();
      struct.setKeyIsSet(true);
      {
        org.apache.thrift.protocol.TList _list67 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
        struct.children = new java.util.ArrayList<ThriftDataNode>(_list67.size);
        @org.apache.thrift.annotation.Nullable ThriftDataNode _elem68;
        for (int _i69 = 0; _i69 < _list67.size; ++_i69)
        {
          _elem68 = new ThriftDataNode();
          _elem68.read(iprot);
          struct.children.add(_elem68);
        }
      }
      struct.setChildrenIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(8);
      if (incoming.get(0)) {
        struct.projectData = new ThriftProjectData();
        struct.projectData.read(iprot);
        struct.setProjectDataIsSet(true);
      }
      if (incoming.get(1)) {
        struct.moduleData = new ThriftModuleData();
        struct.moduleData.read(iprot);
        struct.setModuleDataIsSet(true);
      }
      if (incoming.get(2)) {
        struct.libraryData = new ThriftLibraryData();
        struct.libraryData.read(iprot);
        struct.setLibraryDataIsSet(true);
      }
      if (incoming.get(3)) {
        struct.contentRootData = new ThriftContentRootData();
        struct.contentRootData.read(iprot);
        struct.setContentRootDataIsSet(true);
      }
      if (incoming.get(4)) {
        struct.moduleDependencyData = new ThriftModuleDependencyData();
        struct.moduleDependencyData.read(iprot);
        struct.setModuleDependencyDataIsSet(true);
      }
      if (incoming.get(5)) {
        struct.libraryDependencyData = new ThriftLibraryDependencyData();
        struct.libraryDependencyData.read(iprot);
        struct.setLibraryDependencyDataIsSet(true);
      }
      if (incoming.get(6)) {
        struct.taskData = new ThriftTaskData();
        struct.taskData.read(iprot);
        struct.setTaskDataIsSet(true);
      }
      if (incoming.get(7)) {
        struct.extensionData = iprot.readBinary();
        struct.setExtensionDataIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

