/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.externalSystem.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ThriftLibraryDependencyData implements org.apache.thrift.TBase<ThriftLibraryDependencyData, ThriftLibraryDependencyData._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftLibraryDependencyData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftLibraryDependencyData");

  private static final org.apache.thrift.protocol.TField OWNER_FIELD_DESC = new org.apache.thrift.protocol.TField("owner", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField OWNER_MODULE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("ownerModuleId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField TARGET_LIBRARY_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("targetLibraryName", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField SCOPE_FIELD_DESC = new org.apache.thrift.protocol.TField("scope", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField EXPORTED_FIELD_DESC = new org.apache.thrift.protocol.TField("exported", org.apache.thrift.protocol.TType.BOOL, (short)5);
  private static final org.apache.thrift.protocol.TField LEVEL_FIELD_DESC = new org.apache.thrift.protocol.TField("level", org.apache.thrift.protocol.TType.I32, (short)6);
  private static final org.apache.thrift.protocol.TField TARGET_FIELD_DESC = new org.apache.thrift.protocol.TField("target", org.apache.thrift.protocol.TType.STRUCT, (short)7);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftLibraryDependencyDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftLibraryDependencyDataTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable ThriftProjectSystemId owner; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String ownerModuleId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String targetLibraryName; // required
  /**
   * 
   * @see ThriftDependencyScope
   */
  public @org.apache.thrift.annotation.Nullable ThriftDependencyScope scope; // required
  public boolean exported; // required
  /**
   * 
   * @see ThriftLibraryLevel
   */
  public @org.apache.thrift.annotation.Nullable ThriftLibraryLevel level; // required
  public @org.apache.thrift.annotation.Nullable ThriftLibraryData target; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    OWNER((short)1, "owner"),
    OWNER_MODULE_ID((short)2, "ownerModuleId"),
    TARGET_LIBRARY_NAME((short)3, "targetLibraryName"),
    /**
     * 
     * @see ThriftDependencyScope
     */
    SCOPE((short)4, "scope"),
    EXPORTED((short)5, "exported"),
    /**
     * 
     * @see ThriftLibraryLevel
     */
    LEVEL((short)6, "level"),
    TARGET((short)7, "target");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // OWNER
          return OWNER;
        case 2: // OWNER_MODULE_ID
          return OWNER_MODULE_ID;
        case 3: // TARGET_LIBRARY_NAME
          return TARGET_LIBRARY_NAME;
        case 4: // SCOPE
          return SCOPE;
        case 5: // EXPORTED
          return EXPORTED;
        case 6: // LEVEL
          return LEVEL;
        case 7: // TARGET
          return TARGET;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __EXPORTED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.OWNER, new org.apache.thrift.meta_data.FieldMetaData("owner", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftProjectSystemId.class)));
    tmpMap.put(_Fields.OWNER_MODULE_ID, new org.apache.thrift.meta_data.FieldMetaData("ownerModuleId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TARGET_LIBRARY_NAME, new org.apache.thrift.meta_data.FieldMetaData("targetLibraryName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SCOPE, new org.apache.thrift.meta_data.FieldMetaData("scope", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftDependencyScope.class)));
    tmpMap.put(_Fields.EXPORTED, new org.apache.thrift.meta_data.FieldMetaData("exported", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.LEVEL, new org.apache.thrift.meta_data.FieldMetaData("level", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftLibraryLevel.class)));
    tmpMap.put(_Fields.TARGET, new org.apache.thrift.meta_data.FieldMetaData("target", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftLibraryData.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftLibraryDependencyData.class, metaDataMap);
  }

  public ThriftLibraryDependencyData() {
  }

  public ThriftLibraryDependencyData(
    ThriftProjectSystemId owner,
    java.lang.String ownerModuleId,
    java.lang.String targetLibraryName,
    ThriftDependencyScope scope,
    boolean exported,
    ThriftLibraryLevel level,
    ThriftLibraryData target)
  {
    this();
    this.owner = owner;
    this.ownerModuleId = ownerModuleId;
    this.targetLibraryName = targetLibraryName;
    this.scope = scope;
    this.exported = exported;
    setExportedIsSet(true);
    this.level = level;
    this.target = target;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftLibraryDependencyData(ThriftLibraryDependencyData other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetOwner()) {
      this.owner = new ThriftProjectSystemId(other.owner);
    }
    if (other.isSetOwnerModuleId()) {
      this.ownerModuleId = other.ownerModuleId;
    }
    if (other.isSetTargetLibraryName()) {
      this.targetLibraryName = other.targetLibraryName;
    }
    if (other.isSetScope()) {
      this.scope = other.scope;
    }
    this.exported = other.exported;
    if (other.isSetLevel()) {
      this.level = other.level;
    }
    if (other.isSetTarget()) {
      this.target = new ThriftLibraryData(other.target);
    }
  }

  @Override
  public ThriftLibraryDependencyData deepCopy() {
    return new ThriftLibraryDependencyData(this);
  }

  @Override
  public void clear() {
    this.owner = null;
    this.ownerModuleId = null;
    this.targetLibraryName = null;
    this.scope = null;
    setExportedIsSet(false);
    this.exported = false;
    this.level = null;
    this.target = null;
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftProjectSystemId getOwner() {
    return this.owner;
  }

  public ThriftLibraryDependencyData setOwner(@org.apache.thrift.annotation.Nullable ThriftProjectSystemId owner) {
    this.owner = owner;
    return this;
  }

  public void unsetOwner() {
    this.owner = null;
  }

  /** Returns true if field owner is set (has been assigned a value) and false otherwise */
  public boolean isSetOwner() {
    return this.owner != null;
  }

  public void setOwnerIsSet(boolean value) {
    if (!value) {
      this.owner = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOwnerModuleId() {
    return this.ownerModuleId;
  }

  public ThriftLibraryDependencyData setOwnerModuleId(@org.apache.thrift.annotation.Nullable java.lang.String ownerModuleId) {
    this.ownerModuleId = ownerModuleId;
    return this;
  }

  public void unsetOwnerModuleId() {
    this.ownerModuleId = null;
  }

  /** Returns true if field ownerModuleId is set (has been assigned a value) and false otherwise */
  public boolean isSetOwnerModuleId() {
    return this.ownerModuleId != null;
  }

  public void setOwnerModuleIdIsSet(boolean value) {
    if (!value) {
      this.ownerModuleId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTargetLibraryName() {
    return this.targetLibraryName;
  }

  public ThriftLibraryDependencyData setTargetLibraryName(@org.apache.thrift.annotation.Nullable java.lang.String targetLibraryName) {
    this.targetLibraryName = targetLibraryName;
    return this;
  }

  public void unsetTargetLibraryName() {
    this.targetLibraryName = null;
  }

  /** Returns true if field targetLibraryName is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetLibraryName() {
    return this.targetLibraryName != null;
  }

  public void setTargetLibraryNameIsSet(boolean value) {
    if (!value) {
      this.targetLibraryName = null;
    }
  }

  /**
   * 
   * @see ThriftDependencyScope
   */
  @org.apache.thrift.annotation.Nullable
  public ThriftDependencyScope getScope() {
    return this.scope;
  }

  /**
   * 
   * @see ThriftDependencyScope
   */
  public ThriftLibraryDependencyData setScope(@org.apache.thrift.annotation.Nullable ThriftDependencyScope scope) {
    this.scope = scope;
    return this;
  }

  public void unsetScope() {
    this.scope = null;
  }

  /** Returns true if field scope is set (has been assigned a value) and false otherwise */
  public boolean isSetScope() {
    return this.scope != null;
  }

  public void setScopeIsSet(boolean value) {
    if (!value) {
      this.scope = null;
    }
  }

  public boolean isExported() {
    return this.exported;
  }

  public ThriftLibraryDependencyData setExported(boolean exported) {
    this.exported = exported;
    setExportedIsSet(true);
    return this;
  }

  public void unsetExported() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EXPORTED_ISSET_ID);
  }

  /** Returns true if field exported is set (has been assigned a value) and false otherwise */
  public boolean isSetExported() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EXPORTED_ISSET_ID);
  }

  public void setExportedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EXPORTED_ISSET_ID, value);
  }

  /**
   * 
   * @see ThriftLibraryLevel
   */
  @org.apache.thrift.annotation.Nullable
  public ThriftLibraryLevel getLevel() {
    return this.level;
  }

  /**
   * 
   * @see ThriftLibraryLevel
   */
  public ThriftLibraryDependencyData setLevel(@org.apache.thrift.annotation.Nullable ThriftLibraryLevel level) {
    this.level = level;
    return this;
  }

  public void unsetLevel() {
    this.level = null;
  }

  /** Returns true if field level is set (has been assigned a value) and false otherwise */
  public boolean isSetLevel() {
    return this.level != null;
  }

  public void setLevelIsSet(boolean value) {
    if (!value) {
      this.level = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftLibraryData getTarget() {
    return this.target;
  }

  public ThriftLibraryDependencyData setTarget(@org.apache.thrift.annotation.Nullable ThriftLibraryData target) {
    this.target = target;
    return this;
  }

  public void unsetTarget() {
    this.target = null;
  }

  /** Returns true if field target is set (has been assigned a value) and false otherwise */
  public boolean isSetTarget() {
    return this.target != null;
  }

  public void setTargetIsSet(boolean value) {
    if (!value) {
      this.target = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case OWNER:
      if (value == null) {
        unsetOwner();
      } else {
        setOwner((ThriftProjectSystemId)value);
      }
      break;

    case OWNER_MODULE_ID:
      if (value == null) {
        unsetOwnerModuleId();
      } else {
        setOwnerModuleId((java.lang.String)value);
      }
      break;

    case TARGET_LIBRARY_NAME:
      if (value == null) {
        unsetTargetLibraryName();
      } else {
        setTargetLibraryName((java.lang.String)value);
      }
      break;

    case SCOPE:
      if (value == null) {
        unsetScope();
      } else {
        setScope((ThriftDependencyScope)value);
      }
      break;

    case EXPORTED:
      if (value == null) {
        unsetExported();
      } else {
        setExported((java.lang.Boolean)value);
      }
      break;

    case LEVEL:
      if (value == null) {
        unsetLevel();
      } else {
        setLevel((ThriftLibraryLevel)value);
      }
      break;

    case TARGET:
      if (value == null) {
        unsetTarget();
      } else {
        setTarget((ThriftLibraryData)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case OWNER:
      return getOwner();

    case OWNER_MODULE_ID:
      return getOwnerModuleId();

    case TARGET_LIBRARY_NAME:
      return getTargetLibraryName();

    case SCOPE:
      return getScope();

    case EXPORTED:
      return isExported();

    case LEVEL:
      return getLevel();

    case TARGET:
      return getTarget();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case OWNER:
      return isSetOwner();
    case OWNER_MODULE_ID:
      return isSetOwnerModuleId();
    case TARGET_LIBRARY_NAME:
      return isSetTargetLibraryName();
    case SCOPE:
      return isSetScope();
    case EXPORTED:
      return isSetExported();
    case LEVEL:
      return isSetLevel();
    case TARGET:
      return isSetTarget();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ThriftLibraryDependencyData)
      return this.equals((ThriftLibraryDependencyData)that);
    return false;
  }

  public boolean equals(ThriftLibraryDependencyData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_owner = true && this.isSetOwner();
    boolean that_present_owner = true && that.isSetOwner();
    if (this_present_owner || that_present_owner) {
      if (!(this_present_owner && that_present_owner))
        return false;
      if (!this.owner.equals(that.owner))
        return false;
    }

    boolean this_present_ownerModuleId = true && this.isSetOwnerModuleId();
    boolean that_present_ownerModuleId = true && that.isSetOwnerModuleId();
    if (this_present_ownerModuleId || that_present_ownerModuleId) {
      if (!(this_present_ownerModuleId && that_present_ownerModuleId))
        return false;
      if (!this.ownerModuleId.equals(that.ownerModuleId))
        return false;
    }

    boolean this_present_targetLibraryName = true && this.isSetTargetLibraryName();
    boolean that_present_targetLibraryName = true && that.isSetTargetLibraryName();
    if (this_present_targetLibraryName || that_present_targetLibraryName) {
      if (!(this_present_targetLibraryName && that_present_targetLibraryName))
        return false;
      if (!this.targetLibraryName.equals(that.targetLibraryName))
        return false;
    }

    boolean this_present_scope = true && this.isSetScope();
    boolean that_present_scope = true && that.isSetScope();
    if (this_present_scope || that_present_scope) {
      if (!(this_present_scope && that_present_scope))
        return false;
      if (!this.scope.equals(that.scope))
        return false;
    }

    boolean this_present_exported = true;
    boolean that_present_exported = true;
    if (this_present_exported || that_present_exported) {
      if (!(this_present_exported && that_present_exported))
        return false;
      if (this.exported != that.exported)
        return false;
    }

    boolean this_present_level = true && this.isSetLevel();
    boolean that_present_level = true && that.isSetLevel();
    if (this_present_level || that_present_level) {
      if (!(this_present_level && that_present_level))
        return false;
      if (!this.level.equals(that.level))
        return false;
    }

    boolean this_present_target = true && this.isSetTarget();
    boolean that_present_target = true && that.isSetTarget();
    if (this_present_target || that_present_target) {
      if (!(this_present_target && that_present_target))
        return false;
      if (!this.target.equals(that.target))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetOwner()) ? 131071 : 524287);
    if (isSetOwner())
      hashCode = hashCode * 8191 + owner.hashCode();

    hashCode = hashCode * 8191 + ((isSetOwnerModuleId()) ? 131071 : 524287);
    if (isSetOwnerModuleId())
      hashCode = hashCode * 8191 + ownerModuleId.hashCode();

    hashCode = hashCode * 8191 + ((isSetTargetLibraryName()) ? 131071 : 524287);
    if (isSetTargetLibraryName())
      hashCode = hashCode * 8191 + targetLibraryName.hashCode();

    hashCode = hashCode * 8191 + ((isSetScope()) ? 131071 : 524287);
    if (isSetScope())
      hashCode = hashCode * 8191 + scope.getValue();

    hashCode = hashCode * 8191 + ((exported) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetLevel()) ? 131071 : 524287);
    if (isSetLevel())
      hashCode = hashCode * 8191 + level.getValue();

    hashCode = hashCode * 8191 + ((isSetTarget()) ? 131071 : 524287);
    if (isSetTarget())
      hashCode = hashCode * 8191 + target.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ThriftLibraryDependencyData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetOwner(), other.isSetOwner());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwner()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.owner, other.owner);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOwnerModuleId(), other.isSetOwnerModuleId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwnerModuleId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ownerModuleId, other.ownerModuleId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTargetLibraryName(), other.isSetTargetLibraryName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetLibraryName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetLibraryName, other.targetLibraryName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetScope(), other.isSetScope());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScope()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.scope, other.scope);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetExported(), other.isSetExported());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExported()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.exported, other.exported);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLevel(), other.isSetLevel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLevel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.level, other.level);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTarget(), other.isSetTarget());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTarget()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.target, other.target);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftLibraryDependencyData(");
    boolean first = true;

    sb.append("owner:");
    if (this.owner == null) {
      sb.append("null");
    } else {
      sb.append(this.owner);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ownerModuleId:");
    if (this.ownerModuleId == null) {
      sb.append("null");
    } else {
      sb.append(this.ownerModuleId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("targetLibraryName:");
    if (this.targetLibraryName == null) {
      sb.append("null");
    } else {
      sb.append(this.targetLibraryName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("scope:");
    if (this.scope == null) {
      sb.append("null");
    } else {
      sb.append(this.scope);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("exported:");
    sb.append(this.exported);
    first = false;
    if (!first) sb.append(", ");
    sb.append("level:");
    if (this.level == null) {
      sb.append("null");
    } else {
      sb.append(this.level);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("target:");
    if (this.target == null) {
      sb.append("null");
    } else {
      sb.append(this.target);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (owner == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'owner' was not present! Struct: " + toString());
    }
    if (ownerModuleId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'ownerModuleId' was not present! Struct: " + toString());
    }
    if (targetLibraryName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'targetLibraryName' was not present! Struct: " + toString());
    }
    if (scope == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'scope' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'exported' because it's a primitive and you chose the non-beans generator.
    if (level == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'level' was not present! Struct: " + toString());
    }
    if (target == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'target' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (owner != null) {
      owner.validate();
    }
    if (target != null) {
      target.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftLibraryDependencyDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftLibraryDependencyDataStandardScheme getScheme() {
      return new ThriftLibraryDependencyDataStandardScheme();
    }
  }

  private static class ThriftLibraryDependencyDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftLibraryDependencyData> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftLibraryDependencyData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // OWNER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.owner = new ThriftProjectSystemId();
              struct.owner.read(iprot);
              struct.setOwnerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OWNER_MODULE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ownerModuleId = iprot.readString();
              struct.setOwnerModuleIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TARGET_LIBRARY_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.targetLibraryName = iprot.readString();
              struct.setTargetLibraryNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SCOPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.scope = consulo.externalSystem.thrift.ThriftDependencyScope.findByValue(iprot.readI32());
              struct.setScopeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // EXPORTED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.exported = iprot.readBool();
              struct.setExportedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // LEVEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.level = consulo.externalSystem.thrift.ThriftLibraryLevel.findByValue(iprot.readI32());
              struct.setLevelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TARGET
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.target = new ThriftLibraryData();
              struct.target.read(iprot);
              struct.setTargetIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetExported()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'exported' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftLibraryDependencyData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.owner != null) {
        oprot.writeFieldBegin(OWNER_FIELD_DESC);
        struct.owner.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.ownerModuleId != null) {
        oprot.writeFieldBegin(OWNER_MODULE_ID_FIELD_DESC);
        oprot.writeString(struct.ownerModuleId);
        oprot.writeFieldEnd();
      }
      if (struct.targetLibraryName != null) {
        oprot.writeFieldBegin(TARGET_LIBRARY_NAME_FIELD_DESC);
        oprot.writeString(struct.targetLibraryName);
        oprot.writeFieldEnd();
      }
      if (struct.scope != null) {
        oprot.writeFieldBegin(SCOPE_FIELD_DESC);
        oprot.writeI32(struct.scope.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(EXPORTED_FIELD_DESC);
      oprot.writeBool(struct.exported);
      oprot.writeFieldEnd();
      if (struct.level != null) {
        oprot.writeFieldBegin(LEVEL_FIELD_DESC);
        oprot.writeI32(struct.level.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.target != null) {
        oprot.writeFieldBegin(TARGET_FIELD_DESC);
        struct.target.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftLibraryDependencyDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftLibraryDependencyDataTupleScheme getScheme() {
      return new ThriftLibraryDependencyDataTupleScheme();
    }
  }

  private static class ThriftLibraryDependencyDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftLibraryDependencyData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftLibraryDependencyData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.owner.write(oprot);
      oprot.writeString(struct.ownerModuleId);
      oprot.writeString(struct.targetLibraryName);
      oprot.writeI32(struct.scope.getValue());
      oprot.writeBool(struct.exported);
      oprot.writeI32(struct.level.getValue());
      struct.target.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftLibraryDependencyData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.owner = new ThriftProjectSystemId();
      struct.owner.read(iprot);
      struct.setOwnerIsSet(true);
      struct.ownerModuleId = iprot.readString();
      struct.setOwnerModuleIdIsSet(true);
      struct.targetLibraryName = iprot.readString();
      struct.setTargetLibraryNameIsSet(true);
      struct.scope = consulo.externalSystem.thrift.ThriftDependencyScope.findByValue(iprot.readI32());
      struct.setScopeIsSet(true);
      struct.exported = iprot.readBool();
      struct.setExportedIsSet(true);
      struct.level = consulo.externalSystem.thrift.ThriftLibraryLevel.findByValue(iprot.readI32());
      struct.setLevelIsSet(true);
      struct.target = new ThriftLibraryData();
      struct.target.read(iprot);
      struct.setTargetIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

