/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.externalSystem.thrift;


public enum ThriftProgressEventType implements org.apache.thrift.TEnum {
  QUEUED(0),
  START(1),
  STATUS_CHANGE(2),
  TASK_OUTPUT(3),
  END(4),
  SUCCESS(5),
  FAILURE(6);

  private final int value;

  private ThriftProgressEventType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ThriftProgressEventType findByValue(int value) { 
    switch (value) {
      case 0:
        return QUEUED;
      case 1:
        return START;
      case 2:
        return STATUS_CHANGE;
      case 3:
        return TASK_OUTPUT;
      case 4:
        return END;
      case 5:
        return SUCCESS;
      case 6:
        return FAILURE;
      default:
        return null;
    }
  }
}
