/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.externalSystem.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ThriftLibraryData implements org.apache.thrift.TBase<ThriftLibraryData, ThriftLibraryData._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftLibraryData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftLibraryData");

  private static final org.apache.thrift.protocol.TField EXTERNAL_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("externalName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INTERNAL_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("internalName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField OWNER_FIELD_DESC = new org.apache.thrift.protocol.TField("owner", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField UNRESOLVED_FIELD_DESC = new org.apache.thrift.protocol.TField("unresolved", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField PATHS_FIELD_DESC = new org.apache.thrift.protocol.TField("paths", org.apache.thrift.protocol.TType.MAP, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftLibraryDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftLibraryDataTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String externalName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String internalName; // required
  public @org.apache.thrift.annotation.Nullable ThriftProjectSystemId owner; // required
  public boolean unresolved; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<ThriftLibraryPathType,java.util.List<java.lang.String>> paths; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EXTERNAL_NAME((short)1, "externalName"),
    INTERNAL_NAME((short)2, "internalName"),
    OWNER((short)3, "owner"),
    UNRESOLVED((short)4, "unresolved"),
    PATHS((short)5, "paths");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EXTERNAL_NAME
          return EXTERNAL_NAME;
        case 2: // INTERNAL_NAME
          return INTERNAL_NAME;
        case 3: // OWNER
          return OWNER;
        case 4: // UNRESOLVED
          return UNRESOLVED;
        case 5: // PATHS
          return PATHS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __UNRESOLVED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EXTERNAL_NAME, new org.apache.thrift.meta_data.FieldMetaData("externalName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INTERNAL_NAME, new org.apache.thrift.meta_data.FieldMetaData("internalName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OWNER, new org.apache.thrift.meta_data.FieldMetaData("owner", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftProjectSystemId.class)));
    tmpMap.put(_Fields.UNRESOLVED, new org.apache.thrift.meta_data.FieldMetaData("unresolved", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.PATHS, new org.apache.thrift.meta_data.FieldMetaData("paths", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ThriftLibraryPathType.class), 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftLibraryData.class, metaDataMap);
  }

  public ThriftLibraryData() {
  }

  public ThriftLibraryData(
    java.lang.String externalName,
    java.lang.String internalName,
    ThriftProjectSystemId owner,
    boolean unresolved,
    java.util.Map<ThriftLibraryPathType,java.util.List<java.lang.String>> paths)
  {
    this();
    this.externalName = externalName;
    this.internalName = internalName;
    this.owner = owner;
    this.unresolved = unresolved;
    setUnresolvedIsSet(true);
    this.paths = paths;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftLibraryData(ThriftLibraryData other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetExternalName()) {
      this.externalName = other.externalName;
    }
    if (other.isSetInternalName()) {
      this.internalName = other.internalName;
    }
    if (other.isSetOwner()) {
      this.owner = new ThriftProjectSystemId(other.owner);
    }
    this.unresolved = other.unresolved;
    if (other.isSetPaths()) {
      java.util.Map<ThriftLibraryPathType,java.util.List<java.lang.String>> __this__paths = new java.util.EnumMap<ThriftLibraryPathType,java.util.List<java.lang.String>>(ThriftLibraryPathType.class);
      for (java.util.Map.Entry<ThriftLibraryPathType, java.util.List<java.lang.String>> other_element : other.paths.entrySet()) {

        ThriftLibraryPathType other_element_key = other_element.getKey();
        java.util.List<java.lang.String> other_element_value = other_element.getValue();

        ThriftLibraryPathType __this__paths_copy_key = other_element_key;

        java.util.List<java.lang.String> __this__paths_copy_value = new java.util.ArrayList<java.lang.String>(other_element_value);

        __this__paths.put(__this__paths_copy_key, __this__paths_copy_value);
      }
      this.paths = __this__paths;
    }
  }

  @Override
  public ThriftLibraryData deepCopy() {
    return new ThriftLibraryData(this);
  }

  @Override
  public void clear() {
    this.externalName = null;
    this.internalName = null;
    this.owner = null;
    setUnresolvedIsSet(false);
    this.unresolved = false;
    this.paths = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getExternalName() {
    return this.externalName;
  }

  public ThriftLibraryData setExternalName(@org.apache.thrift.annotation.Nullable java.lang.String externalName) {
    this.externalName = externalName;
    return this;
  }

  public void unsetExternalName() {
    this.externalName = null;
  }

  /** Returns true if field externalName is set (has been assigned a value) and false otherwise */
  public boolean isSetExternalName() {
    return this.externalName != null;
  }

  public void setExternalNameIsSet(boolean value) {
    if (!value) {
      this.externalName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getInternalName() {
    return this.internalName;
  }

  public ThriftLibraryData setInternalName(@org.apache.thrift.annotation.Nullable java.lang.String internalName) {
    this.internalName = internalName;
    return this;
  }

  public void unsetInternalName() {
    this.internalName = null;
  }

  /** Returns true if field internalName is set (has been assigned a value) and false otherwise */
  public boolean isSetInternalName() {
    return this.internalName != null;
  }

  public void setInternalNameIsSet(boolean value) {
    if (!value) {
      this.internalName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftProjectSystemId getOwner() {
    return this.owner;
  }

  public ThriftLibraryData setOwner(@org.apache.thrift.annotation.Nullable ThriftProjectSystemId owner) {
    this.owner = owner;
    return this;
  }

  public void unsetOwner() {
    this.owner = null;
  }

  /** Returns true if field owner is set (has been assigned a value) and false otherwise */
  public boolean isSetOwner() {
    return this.owner != null;
  }

  public void setOwnerIsSet(boolean value) {
    if (!value) {
      this.owner = null;
    }
  }

  public boolean isUnresolved() {
    return this.unresolved;
  }

  public ThriftLibraryData setUnresolved(boolean unresolved) {
    this.unresolved = unresolved;
    setUnresolvedIsSet(true);
    return this;
  }

  public void unsetUnresolved() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __UNRESOLVED_ISSET_ID);
  }

  /** Returns true if field unresolved is set (has been assigned a value) and false otherwise */
  public boolean isSetUnresolved() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __UNRESOLVED_ISSET_ID);
  }

  public void setUnresolvedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __UNRESOLVED_ISSET_ID, value);
  }

  public int getPathsSize() {
    return (this.paths == null) ? 0 : this.paths.size();
  }

  public void putToPaths(ThriftLibraryPathType key, java.util.List<java.lang.String> val) {
    if (this.paths == null) {
      this.paths = new java.util.EnumMap<ThriftLibraryPathType,java.util.List<java.lang.String>>(ThriftLibraryPathType.class);
    }
    this.paths.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<ThriftLibraryPathType,java.util.List<java.lang.String>> getPaths() {
    return this.paths;
  }

  public ThriftLibraryData setPaths(@org.apache.thrift.annotation.Nullable java.util.Map<ThriftLibraryPathType,java.util.List<java.lang.String>> paths) {
    this.paths = paths;
    return this;
  }

  public void unsetPaths() {
    this.paths = null;
  }

  /** Returns true if field paths is set (has been assigned a value) and false otherwise */
  public boolean isSetPaths() {
    return this.paths != null;
  }

  public void setPathsIsSet(boolean value) {
    if (!value) {
      this.paths = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case EXTERNAL_NAME:
      if (value == null) {
        unsetExternalName();
      } else {
        setExternalName((java.lang.String)value);
      }
      break;

    case INTERNAL_NAME:
      if (value == null) {
        unsetInternalName();
      } else {
        setInternalName((java.lang.String)value);
      }
      break;

    case OWNER:
      if (value == null) {
        unsetOwner();
      } else {
        setOwner((ThriftProjectSystemId)value);
      }
      break;

    case UNRESOLVED:
      if (value == null) {
        unsetUnresolved();
      } else {
        setUnresolved((java.lang.Boolean)value);
      }
      break;

    case PATHS:
      if (value == null) {
        unsetPaths();
      } else {
        setPaths((java.util.Map<ThriftLibraryPathType,java.util.List<java.lang.String>>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case EXTERNAL_NAME:
      return getExternalName();

    case INTERNAL_NAME:
      return getInternalName();

    case OWNER:
      return getOwner();

    case UNRESOLVED:
      return isUnresolved();

    case PATHS:
      return getPaths();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case EXTERNAL_NAME:
      return isSetExternalName();
    case INTERNAL_NAME:
      return isSetInternalName();
    case OWNER:
      return isSetOwner();
    case UNRESOLVED:
      return isSetUnresolved();
    case PATHS:
      return isSetPaths();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ThriftLibraryData)
      return this.equals((ThriftLibraryData)that);
    return false;
  }

  public boolean equals(ThriftLibraryData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_externalName = true && this.isSetExternalName();
    boolean that_present_externalName = true && that.isSetExternalName();
    if (this_present_externalName || that_present_externalName) {
      if (!(this_present_externalName && that_present_externalName))
        return false;
      if (!this.externalName.equals(that.externalName))
        return false;
    }

    boolean this_present_internalName = true && this.isSetInternalName();
    boolean that_present_internalName = true && that.isSetInternalName();
    if (this_present_internalName || that_present_internalName) {
      if (!(this_present_internalName && that_present_internalName))
        return false;
      if (!this.internalName.equals(that.internalName))
        return false;
    }

    boolean this_present_owner = true && this.isSetOwner();
    boolean that_present_owner = true && that.isSetOwner();
    if (this_present_owner || that_present_owner) {
      if (!(this_present_owner && that_present_owner))
        return false;
      if (!this.owner.equals(that.owner))
        return false;
    }

    boolean this_present_unresolved = true;
    boolean that_present_unresolved = true;
    if (this_present_unresolved || that_present_unresolved) {
      if (!(this_present_unresolved && that_present_unresolved))
        return false;
      if (this.unresolved != that.unresolved)
        return false;
    }

    boolean this_present_paths = true && this.isSetPaths();
    boolean that_present_paths = true && that.isSetPaths();
    if (this_present_paths || that_present_paths) {
      if (!(this_present_paths && that_present_paths))
        return false;
      if (!this.paths.equals(that.paths))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetExternalName()) ? 131071 : 524287);
    if (isSetExternalName())
      hashCode = hashCode * 8191 + externalName.hashCode();

    hashCode = hashCode * 8191 + ((isSetInternalName()) ? 131071 : 524287);
    if (isSetInternalName())
      hashCode = hashCode * 8191 + internalName.hashCode();

    hashCode = hashCode * 8191 + ((isSetOwner()) ? 131071 : 524287);
    if (isSetOwner())
      hashCode = hashCode * 8191 + owner.hashCode();

    hashCode = hashCode * 8191 + ((unresolved) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetPaths()) ? 131071 : 524287);
    if (isSetPaths())
      hashCode = hashCode * 8191 + paths.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ThriftLibraryData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetExternalName(), other.isSetExternalName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExternalName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.externalName, other.externalName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetInternalName(), other.isSetInternalName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInternalName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.internalName, other.internalName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOwner(), other.isSetOwner());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwner()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.owner, other.owner);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUnresolved(), other.isSetUnresolved());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUnresolved()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.unresolved, other.unresolved);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPaths(), other.isSetPaths());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPaths()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.paths, other.paths);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftLibraryData(");
    boolean first = true;

    sb.append("externalName:");
    if (this.externalName == null) {
      sb.append("null");
    } else {
      sb.append(this.externalName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("internalName:");
    if (this.internalName == null) {
      sb.append("null");
    } else {
      sb.append(this.internalName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("owner:");
    if (this.owner == null) {
      sb.append("null");
    } else {
      sb.append(this.owner);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("unresolved:");
    sb.append(this.unresolved);
    first = false;
    if (!first) sb.append(", ");
    sb.append("paths:");
    if (this.paths == null) {
      sb.append("null");
    } else {
      sb.append(this.paths);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (externalName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'externalName' was not present! Struct: " + toString());
    }
    if (internalName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'internalName' was not present! Struct: " + toString());
    }
    if (owner == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'owner' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'unresolved' because it's a primitive and you chose the non-beans generator.
    if (paths == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'paths' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (owner != null) {
      owner.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftLibraryDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftLibraryDataStandardScheme getScheme() {
      return new ThriftLibraryDataStandardScheme();
    }
  }

  private static class ThriftLibraryDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftLibraryData> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftLibraryData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EXTERNAL_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.externalName = iprot.readString();
              struct.setExternalNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INTERNAL_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.internalName = iprot.readString();
              struct.setInternalNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OWNER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.owner = new ThriftProjectSystemId();
              struct.owner.read(iprot);
              struct.setOwnerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // UNRESOLVED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.unresolved = iprot.readBool();
              struct.setUnresolvedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PATHS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map26 = iprot.readMapBegin();
                struct.paths = new java.util.EnumMap<ThriftLibraryPathType,java.util.List<java.lang.String>>(ThriftLibraryPathType.class);
                @org.apache.thrift.annotation.Nullable ThriftLibraryPathType _key27;
                @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> _val28;
                for (int _i29 = 0; _i29 < _map26.size; ++_i29)
                {
                  _key27 = consulo.externalSystem.thrift.ThriftLibraryPathType.findByValue(iprot.readI32());
                  {
                    org.apache.thrift.protocol.TList _list30 = iprot.readListBegin();
                    _val28 = new java.util.ArrayList<java.lang.String>(_list30.size);
                    @org.apache.thrift.annotation.Nullable java.lang.String _elem31;
                    for (int _i32 = 0; _i32 < _list30.size; ++_i32)
                    {
                      _elem31 = iprot.readString();
                      _val28.add(_elem31);
                    }
                    iprot.readListEnd();
                  }
                  if (_key27 != null)
                  {
                    struct.paths.put(_key27, _val28);
                  }
                }
                iprot.readMapEnd();
              }
              struct.setPathsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetUnresolved()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'unresolved' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftLibraryData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.externalName != null) {
        oprot.writeFieldBegin(EXTERNAL_NAME_FIELD_DESC);
        oprot.writeString(struct.externalName);
        oprot.writeFieldEnd();
      }
      if (struct.internalName != null) {
        oprot.writeFieldBegin(INTERNAL_NAME_FIELD_DESC);
        oprot.writeString(struct.internalName);
        oprot.writeFieldEnd();
      }
      if (struct.owner != null) {
        oprot.writeFieldBegin(OWNER_FIELD_DESC);
        struct.owner.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(UNRESOLVED_FIELD_DESC);
      oprot.writeBool(struct.unresolved);
      oprot.writeFieldEnd();
      if (struct.paths != null) {
        oprot.writeFieldBegin(PATHS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.LIST, struct.paths.size()));
          for (java.util.Map.Entry<ThriftLibraryPathType, java.util.List<java.lang.String>> _iter33 : struct.paths.entrySet())
          {
            oprot.writeI32(_iter33.getKey().getValue());
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, _iter33.getValue().size()));
              for (java.lang.String _iter34 : _iter33.getValue())
              {
                oprot.writeString(_iter34);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftLibraryDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftLibraryDataTupleScheme getScheme() {
      return new ThriftLibraryDataTupleScheme();
    }
  }

  private static class ThriftLibraryDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftLibraryData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftLibraryData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.externalName);
      oprot.writeString(struct.internalName);
      struct.owner.write(oprot);
      oprot.writeBool(struct.unresolved);
      {
        oprot.writeI32(struct.paths.size());
        for (java.util.Map.Entry<ThriftLibraryPathType, java.util.List<java.lang.String>> _iter35 : struct.paths.entrySet())
        {
          oprot.writeI32(_iter35.getKey().getValue());
          {
            oprot.writeI32(_iter35.getValue().size());
            for (java.lang.String _iter36 : _iter35.getValue())
            {
              oprot.writeString(_iter36);
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftLibraryData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.externalName = iprot.readString();
      struct.setExternalNameIsSet(true);
      struct.internalName = iprot.readString();
      struct.setInternalNameIsSet(true);
      struct.owner = new ThriftProjectSystemId();
      struct.owner.read(iprot);
      struct.setOwnerIsSet(true);
      struct.unresolved = iprot.readBool();
      struct.setUnresolvedIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map37 = iprot.readMapBegin(org.apache.thrift.protocol.TType.I32, org.apache.thrift.protocol.TType.LIST); 
        struct.paths = new java.util.EnumMap<ThriftLibraryPathType,java.util.List<java.lang.String>>(ThriftLibraryPathType.class);
        @org.apache.thrift.annotation.Nullable ThriftLibraryPathType _key38;
        @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> _val39;
        for (int _i40 = 0; _i40 < _map37.size; ++_i40)
        {
          _key38 = consulo.externalSystem.thrift.ThriftLibraryPathType.findByValue(iprot.readI32());
          {
            org.apache.thrift.protocol.TList _list41 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
            _val39 = new java.util.ArrayList<java.lang.String>(_list41.size);
            @org.apache.thrift.annotation.Nullable java.lang.String _elem42;
            for (int _i43 = 0; _i43 < _list41.size; ++_i43)
            {
              _elem42 = iprot.readString();
              _val39.add(_elem42);
            }
          }
          if (_key38 != null)
          {
            struct.paths.put(_key38, _val39);
          }
        }
      }
      struct.setPathsIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

