/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.externalSystem.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ThriftExternalSystemException extends org.apache.thrift.TException implements org.apache.thrift.TBase<ThriftExternalSystemException, ThriftExternalSystemException._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftExternalSystemException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftExternalSystemException");

  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField ORIGINAL_REASON_FIELD_DESC = new org.apache.thrift.protocol.TField("originalReason", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField QUICK_FIXES_FIELD_DESC = new org.apache.thrift.protocol.TField("quickFixes", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField FILE_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("filePath", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField LINE_FIELD_DESC = new org.apache.thrift.protocol.TField("line", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField COLUMN_FIELD_DESC = new org.apache.thrift.protocol.TField("column", org.apache.thrift.protocol.TType.I32, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftExternalSystemExceptionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftExternalSystemExceptionTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String message; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String originalReason; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> quickFixes; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String filePath; // optional
  public int line; // optional
  public int column; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE((short)1, "message"),
    ORIGINAL_REASON((short)2, "originalReason"),
    QUICK_FIXES((short)3, "quickFixes"),
    FILE_PATH((short)4, "filePath"),
    LINE((short)5, "line"),
    COLUMN((short)6, "column");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE
          return MESSAGE;
        case 2: // ORIGINAL_REASON
          return ORIGINAL_REASON;
        case 3: // QUICK_FIXES
          return QUICK_FIXES;
        case 4: // FILE_PATH
          return FILE_PATH;
        case 5: // LINE
          return LINE;
        case 6: // COLUMN
          return COLUMN;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LINE_ISSET_ID = 0;
  private static final int __COLUMN_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.FILE_PATH,_Fields.LINE,_Fields.COLUMN};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ORIGINAL_REASON, new org.apache.thrift.meta_data.FieldMetaData("originalReason", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.QUICK_FIXES, new org.apache.thrift.meta_data.FieldMetaData("quickFixes", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.FILE_PATH, new org.apache.thrift.meta_data.FieldMetaData("filePath", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LINE, new org.apache.thrift.meta_data.FieldMetaData("line", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.COLUMN, new org.apache.thrift.meta_data.FieldMetaData("column", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftExternalSystemException.class, metaDataMap);
  }

  public ThriftExternalSystemException() {
  }

  public ThriftExternalSystemException(
    java.lang.String message,
    java.lang.String originalReason,
    java.util.List<java.lang.String> quickFixes)
  {
    this();
    this.message = message;
    this.originalReason = originalReason;
    this.quickFixes = quickFixes;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftExternalSystemException(ThriftExternalSystemException other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMessage()) {
      this.message = other.message;
    }
    if (other.isSetOriginalReason()) {
      this.originalReason = other.originalReason;
    }
    if (other.isSetQuickFixes()) {
      java.util.List<java.lang.String> __this__quickFixes = new java.util.ArrayList<java.lang.String>(other.quickFixes);
      this.quickFixes = __this__quickFixes;
    }
    if (other.isSetFilePath()) {
      this.filePath = other.filePath;
    }
    this.line = other.line;
    this.column = other.column;
  }

  @Override
  public ThriftExternalSystemException deepCopy() {
    return new ThriftExternalSystemException(this);
  }

  @Override
  public void clear() {
    this.message = null;
    this.originalReason = null;
    this.quickFixes = null;
    this.filePath = null;
    setLineIsSet(false);
    this.line = 0;
    setColumnIsSet(false);
    this.column = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMessage() {
    return this.message;
  }

  public ThriftExternalSystemException setMessage(@org.apache.thrift.annotation.Nullable java.lang.String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOriginalReason() {
    return this.originalReason;
  }

  public ThriftExternalSystemException setOriginalReason(@org.apache.thrift.annotation.Nullable java.lang.String originalReason) {
    this.originalReason = originalReason;
    return this;
  }

  public void unsetOriginalReason() {
    this.originalReason = null;
  }

  /** Returns true if field originalReason is set (has been assigned a value) and false otherwise */
  public boolean isSetOriginalReason() {
    return this.originalReason != null;
  }

  public void setOriginalReasonIsSet(boolean value) {
    if (!value) {
      this.originalReason = null;
    }
  }

  public int getQuickFixesSize() {
    return (this.quickFixes == null) ? 0 : this.quickFixes.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getQuickFixesIterator() {
    return (this.quickFixes == null) ? null : this.quickFixes.iterator();
  }

  public void addToQuickFixes(java.lang.String elem) {
    if (this.quickFixes == null) {
      this.quickFixes = new java.util.ArrayList<java.lang.String>();
    }
    this.quickFixes.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getQuickFixes() {
    return this.quickFixes;
  }

  public ThriftExternalSystemException setQuickFixes(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> quickFixes) {
    this.quickFixes = quickFixes;
    return this;
  }

  public void unsetQuickFixes() {
    this.quickFixes = null;
  }

  /** Returns true if field quickFixes is set (has been assigned a value) and false otherwise */
  public boolean isSetQuickFixes() {
    return this.quickFixes != null;
  }

  public void setQuickFixesIsSet(boolean value) {
    if (!value) {
      this.quickFixes = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getFilePath() {
    return this.filePath;
  }

  public ThriftExternalSystemException setFilePath(@org.apache.thrift.annotation.Nullable java.lang.String filePath) {
    this.filePath = filePath;
    return this;
  }

  public void unsetFilePath() {
    this.filePath = null;
  }

  /** Returns true if field filePath is set (has been assigned a value) and false otherwise */
  public boolean isSetFilePath() {
    return this.filePath != null;
  }

  public void setFilePathIsSet(boolean value) {
    if (!value) {
      this.filePath = null;
    }
  }

  public int getLine() {
    return this.line;
  }

  public ThriftExternalSystemException setLine(int line) {
    this.line = line;
    setLineIsSet(true);
    return this;
  }

  public void unsetLine() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LINE_ISSET_ID);
  }

  /** Returns true if field line is set (has been assigned a value) and false otherwise */
  public boolean isSetLine() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LINE_ISSET_ID);
  }

  public void setLineIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LINE_ISSET_ID, value);
  }

  public int getColumn() {
    return this.column;
  }

  public ThriftExternalSystemException setColumn(int column) {
    this.column = column;
    setColumnIsSet(true);
    return this;
  }

  public void unsetColumn() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __COLUMN_ISSET_ID);
  }

  /** Returns true if field column is set (has been assigned a value) and false otherwise */
  public boolean isSetColumn() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __COLUMN_ISSET_ID);
  }

  public void setColumnIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __COLUMN_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((java.lang.String)value);
      }
      break;

    case ORIGINAL_REASON:
      if (value == null) {
        unsetOriginalReason();
      } else {
        setOriginalReason((java.lang.String)value);
      }
      break;

    case QUICK_FIXES:
      if (value == null) {
        unsetQuickFixes();
      } else {
        setQuickFixes((java.util.List<java.lang.String>)value);
      }
      break;

    case FILE_PATH:
      if (value == null) {
        unsetFilePath();
      } else {
        setFilePath((java.lang.String)value);
      }
      break;

    case LINE:
      if (value == null) {
        unsetLine();
      } else {
        setLine((java.lang.Integer)value);
      }
      break;

    case COLUMN:
      if (value == null) {
        unsetColumn();
      } else {
        setColumn((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE:
      return getMessage();

    case ORIGINAL_REASON:
      return getOriginalReason();

    case QUICK_FIXES:
      return getQuickFixes();

    case FILE_PATH:
      return getFilePath();

    case LINE:
      return getLine();

    case COLUMN:
      return getColumn();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE:
      return isSetMessage();
    case ORIGINAL_REASON:
      return isSetOriginalReason();
    case QUICK_FIXES:
      return isSetQuickFixes();
    case FILE_PATH:
      return isSetFilePath();
    case LINE:
      return isSetLine();
    case COLUMN:
      return isSetColumn();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ThriftExternalSystemException)
      return this.equals((ThriftExternalSystemException)that);
    return false;
  }

  public boolean equals(ThriftExternalSystemException that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    boolean this_present_originalReason = true && this.isSetOriginalReason();
    boolean that_present_originalReason = true && that.isSetOriginalReason();
    if (this_present_originalReason || that_present_originalReason) {
      if (!(this_present_originalReason && that_present_originalReason))
        return false;
      if (!this.originalReason.equals(that.originalReason))
        return false;
    }

    boolean this_present_quickFixes = true && this.isSetQuickFixes();
    boolean that_present_quickFixes = true && that.isSetQuickFixes();
    if (this_present_quickFixes || that_present_quickFixes) {
      if (!(this_present_quickFixes && that_present_quickFixes))
        return false;
      if (!this.quickFixes.equals(that.quickFixes))
        return false;
    }

    boolean this_present_filePath = true && this.isSetFilePath();
    boolean that_present_filePath = true && that.isSetFilePath();
    if (this_present_filePath || that_present_filePath) {
      if (!(this_present_filePath && that_present_filePath))
        return false;
      if (!this.filePath.equals(that.filePath))
        return false;
    }

    boolean this_present_line = true && this.isSetLine();
    boolean that_present_line = true && that.isSetLine();
    if (this_present_line || that_present_line) {
      if (!(this_present_line && that_present_line))
        return false;
      if (this.line != that.line)
        return false;
    }

    boolean this_present_column = true && this.isSetColumn();
    boolean that_present_column = true && that.isSetColumn();
    if (this_present_column || that_present_column) {
      if (!(this_present_column && that_present_column))
        return false;
      if (this.column != that.column)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMessage()) ? 131071 : 524287);
    if (isSetMessage())
      hashCode = hashCode * 8191 + message.hashCode();

    hashCode = hashCode * 8191 + ((isSetOriginalReason()) ? 131071 : 524287);
    if (isSetOriginalReason())
      hashCode = hashCode * 8191 + originalReason.hashCode();

    hashCode = hashCode * 8191 + ((isSetQuickFixes()) ? 131071 : 524287);
    if (isSetQuickFixes())
      hashCode = hashCode * 8191 + quickFixes.hashCode();

    hashCode = hashCode * 8191 + ((isSetFilePath()) ? 131071 : 524287);
    if (isSetFilePath())
      hashCode = hashCode * 8191 + filePath.hashCode();

    hashCode = hashCode * 8191 + ((isSetLine()) ? 131071 : 524287);
    if (isSetLine())
      hashCode = hashCode * 8191 + line;

    hashCode = hashCode * 8191 + ((isSetColumn()) ? 131071 : 524287);
    if (isSetColumn())
      hashCode = hashCode * 8191 + column;

    return hashCode;
  }

  @Override
  public int compareTo(ThriftExternalSystemException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetMessage(), other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, other.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOriginalReason(), other.isSetOriginalReason());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOriginalReason()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.originalReason, other.originalReason);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetQuickFixes(), other.isSetQuickFixes());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetQuickFixes()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.quickFixes, other.quickFixes);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFilePath(), other.isSetFilePath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFilePath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.filePath, other.filePath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLine(), other.isSetLine());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLine()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.line, other.line);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetColumn(), other.isSetColumn());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetColumn()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.column, other.column);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftExternalSystemException(");
    boolean first = true;

    sb.append("message:");
    if (this.message == null) {
      sb.append("null");
    } else {
      sb.append(this.message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("originalReason:");
    if (this.originalReason == null) {
      sb.append("null");
    } else {
      sb.append(this.originalReason);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("quickFixes:");
    if (this.quickFixes == null) {
      sb.append("null");
    } else {
      sb.append(this.quickFixes);
    }
    first = false;
    if (isSetFilePath()) {
      if (!first) sb.append(", ");
      sb.append("filePath:");
      if (this.filePath == null) {
        sb.append("null");
      } else {
        sb.append(this.filePath);
      }
      first = false;
    }
    if (isSetLine()) {
      if (!first) sb.append(", ");
      sb.append("line:");
      sb.append(this.line);
      first = false;
    }
    if (isSetColumn()) {
      if (!first) sb.append(", ");
      sb.append("column:");
      sb.append(this.column);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (message == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'message' was not present! Struct: " + toString());
    }
    if (originalReason == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'originalReason' was not present! Struct: " + toString());
    }
    if (quickFixes == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'quickFixes' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftExternalSystemExceptionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftExternalSystemExceptionStandardScheme getScheme() {
      return new ThriftExternalSystemExceptionStandardScheme();
    }
  }

  private static class ThriftExternalSystemExceptionStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftExternalSystemException> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftExternalSystemException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ORIGINAL_REASON
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.originalReason = iprot.readString();
              struct.setOriginalReasonIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // QUICK_FIXES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.quickFixes = new java.util.ArrayList<java.lang.String>(_list0.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = iprot.readString();
                  struct.quickFixes.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setQuickFixesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // FILE_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.filePath = iprot.readString();
              struct.setFilePathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // LINE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.line = iprot.readI32();
              struct.setLineIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // COLUMN
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.column = iprot.readI32();
              struct.setColumnIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftExternalSystemException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(struct.message);
        oprot.writeFieldEnd();
      }
      if (struct.originalReason != null) {
        oprot.writeFieldBegin(ORIGINAL_REASON_FIELD_DESC);
        oprot.writeString(struct.originalReason);
        oprot.writeFieldEnd();
      }
      if (struct.quickFixes != null) {
        oprot.writeFieldBegin(QUICK_FIXES_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.quickFixes.size()));
          for (java.lang.String _iter3 : struct.quickFixes)
          {
            oprot.writeString(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.filePath != null) {
        if (struct.isSetFilePath()) {
          oprot.writeFieldBegin(FILE_PATH_FIELD_DESC);
          oprot.writeString(struct.filePath);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetLine()) {
        oprot.writeFieldBegin(LINE_FIELD_DESC);
        oprot.writeI32(struct.line);
        oprot.writeFieldEnd();
      }
      if (struct.isSetColumn()) {
        oprot.writeFieldBegin(COLUMN_FIELD_DESC);
        oprot.writeI32(struct.column);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftExternalSystemExceptionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftExternalSystemExceptionTupleScheme getScheme() {
      return new ThriftExternalSystemExceptionTupleScheme();
    }
  }

  private static class ThriftExternalSystemExceptionTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftExternalSystemException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftExternalSystemException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.message);
      oprot.writeString(struct.originalReason);
      {
        oprot.writeI32(struct.quickFixes.size());
        for (java.lang.String _iter4 : struct.quickFixes)
        {
          oprot.writeString(_iter4);
        }
      }
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetFilePath()) {
        optionals.set(0);
      }
      if (struct.isSetLine()) {
        optionals.set(1);
      }
      if (struct.isSetColumn()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetFilePath()) {
        oprot.writeString(struct.filePath);
      }
      if (struct.isSetLine()) {
        oprot.writeI32(struct.line);
      }
      if (struct.isSetColumn()) {
        oprot.writeI32(struct.column);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftExternalSystemException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.message = iprot.readString();
      struct.setMessageIsSet(true);
      struct.originalReason = iprot.readString();
      struct.setOriginalReasonIsSet(true);
      {
        org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
        struct.quickFixes = new java.util.ArrayList<java.lang.String>(_list5.size);
        @org.apache.thrift.annotation.Nullable java.lang.String _elem6;
        for (int _i7 = 0; _i7 < _list5.size; ++_i7)
        {
          _elem6 = iprot.readString();
          struct.quickFixes.add(_elem6);
        }
      }
      struct.setQuickFixesIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.filePath = iprot.readString();
        struct.setFilePathIsSet(true);
      }
      if (incoming.get(1)) {
        struct.line = iprot.readI32();
        struct.setLineIsSet(true);
      }
      if (incoming.get(2)) {
        struct.column = iprot.readI32();
        struct.setColumnIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

