/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.externalSystem.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ThriftExecutionSettings implements org.apache.thrift.TBase<ThriftExecutionSettings, ThriftExecutionSettings._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftExecutionSettings> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftExecutionSettings");

  private static final org.apache.thrift.protocol.TField REMOTE_PROCESS_IDLE_TTL_MS_FIELD_DESC = new org.apache.thrift.protocol.TField("remoteProcessIdleTtlMs", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField VERBOSE_PROCESSING_FIELD_DESC = new org.apache.thrift.protocol.TField("verboseProcessing", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField PROPERTIES_FIELD_DESC = new org.apache.thrift.protocol.TField("properties", org.apache.thrift.protocol.TType.MAP, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftExecutionSettingsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftExecutionSettingsTupleSchemeFactory();

  public long remoteProcessIdleTtlMs; // required
  public boolean verboseProcessing; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> properties; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    REMOTE_PROCESS_IDLE_TTL_MS((short)1, "remoteProcessIdleTtlMs"),
    VERBOSE_PROCESSING((short)2, "verboseProcessing"),
    PROPERTIES((short)3, "properties");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // REMOTE_PROCESS_IDLE_TTL_MS
          return REMOTE_PROCESS_IDLE_TTL_MS;
        case 2: // VERBOSE_PROCESSING
          return VERBOSE_PROCESSING;
        case 3: // PROPERTIES
          return PROPERTIES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __REMOTEPROCESSIDLETTLMS_ISSET_ID = 0;
  private static final int __VERBOSEPROCESSING_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.REMOTE_PROCESS_IDLE_TTL_MS, new org.apache.thrift.meta_data.FieldMetaData("remoteProcessIdleTtlMs", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.VERBOSE_PROCESSING, new org.apache.thrift.meta_data.FieldMetaData("verboseProcessing", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.PROPERTIES, new org.apache.thrift.meta_data.FieldMetaData("properties", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftExecutionSettings.class, metaDataMap);
  }

  public ThriftExecutionSettings() {
  }

  public ThriftExecutionSettings(
    long remoteProcessIdleTtlMs,
    boolean verboseProcessing,
    java.util.Map<java.lang.String,java.lang.String> properties)
  {
    this();
    this.remoteProcessIdleTtlMs = remoteProcessIdleTtlMs;
    setRemoteProcessIdleTtlMsIsSet(true);
    this.verboseProcessing = verboseProcessing;
    setVerboseProcessingIsSet(true);
    this.properties = properties;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftExecutionSettings(ThriftExecutionSettings other) {
    __isset_bitfield = other.__isset_bitfield;
    this.remoteProcessIdleTtlMs = other.remoteProcessIdleTtlMs;
    this.verboseProcessing = other.verboseProcessing;
    if (other.isSetProperties()) {
      java.util.Map<java.lang.String,java.lang.String> __this__properties = new java.util.HashMap<java.lang.String,java.lang.String>(other.properties);
      this.properties = __this__properties;
    }
  }

  @Override
  public ThriftExecutionSettings deepCopy() {
    return new ThriftExecutionSettings(this);
  }

  @Override
  public void clear() {
    setRemoteProcessIdleTtlMsIsSet(false);
    this.remoteProcessIdleTtlMs = 0;
    setVerboseProcessingIsSet(false);
    this.verboseProcessing = false;
    this.properties = null;
  }

  public long getRemoteProcessIdleTtlMs() {
    return this.remoteProcessIdleTtlMs;
  }

  public ThriftExecutionSettings setRemoteProcessIdleTtlMs(long remoteProcessIdleTtlMs) {
    this.remoteProcessIdleTtlMs = remoteProcessIdleTtlMs;
    setRemoteProcessIdleTtlMsIsSet(true);
    return this;
  }

  public void unsetRemoteProcessIdleTtlMs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __REMOTEPROCESSIDLETTLMS_ISSET_ID);
  }

  /** Returns true if field remoteProcessIdleTtlMs is set (has been assigned a value) and false otherwise */
  public boolean isSetRemoteProcessIdleTtlMs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __REMOTEPROCESSIDLETTLMS_ISSET_ID);
  }

  public void setRemoteProcessIdleTtlMsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __REMOTEPROCESSIDLETTLMS_ISSET_ID, value);
  }

  public boolean isVerboseProcessing() {
    return this.verboseProcessing;
  }

  public ThriftExecutionSettings setVerboseProcessing(boolean verboseProcessing) {
    this.verboseProcessing = verboseProcessing;
    setVerboseProcessingIsSet(true);
    return this;
  }

  public void unsetVerboseProcessing() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VERBOSEPROCESSING_ISSET_ID);
  }

  /** Returns true if field verboseProcessing is set (has been assigned a value) and false otherwise */
  public boolean isSetVerboseProcessing() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VERBOSEPROCESSING_ISSET_ID);
  }

  public void setVerboseProcessingIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VERBOSEPROCESSING_ISSET_ID, value);
  }

  public int getPropertiesSize() {
    return (this.properties == null) ? 0 : this.properties.size();
  }

  public void putToProperties(java.lang.String key, java.lang.String val) {
    if (this.properties == null) {
      this.properties = new java.util.HashMap<java.lang.String,java.lang.String>();
    }
    this.properties.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.lang.String> getProperties() {
    return this.properties;
  }

  public ThriftExecutionSettings setProperties(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> properties) {
    this.properties = properties;
    return this;
  }

  public void unsetProperties() {
    this.properties = null;
  }

  /** Returns true if field properties is set (has been assigned a value) and false otherwise */
  public boolean isSetProperties() {
    return this.properties != null;
  }

  public void setPropertiesIsSet(boolean value) {
    if (!value) {
      this.properties = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case REMOTE_PROCESS_IDLE_TTL_MS:
      if (value == null) {
        unsetRemoteProcessIdleTtlMs();
      } else {
        setRemoteProcessIdleTtlMs((java.lang.Long)value);
      }
      break;

    case VERBOSE_PROCESSING:
      if (value == null) {
        unsetVerboseProcessing();
      } else {
        setVerboseProcessing((java.lang.Boolean)value);
      }
      break;

    case PROPERTIES:
      if (value == null) {
        unsetProperties();
      } else {
        setProperties((java.util.Map<java.lang.String,java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case REMOTE_PROCESS_IDLE_TTL_MS:
      return getRemoteProcessIdleTtlMs();

    case VERBOSE_PROCESSING:
      return isVerboseProcessing();

    case PROPERTIES:
      return getProperties();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case REMOTE_PROCESS_IDLE_TTL_MS:
      return isSetRemoteProcessIdleTtlMs();
    case VERBOSE_PROCESSING:
      return isSetVerboseProcessing();
    case PROPERTIES:
      return isSetProperties();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ThriftExecutionSettings)
      return this.equals((ThriftExecutionSettings)that);
    return false;
  }

  public boolean equals(ThriftExecutionSettings that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_remoteProcessIdleTtlMs = true;
    boolean that_present_remoteProcessIdleTtlMs = true;
    if (this_present_remoteProcessIdleTtlMs || that_present_remoteProcessIdleTtlMs) {
      if (!(this_present_remoteProcessIdleTtlMs && that_present_remoteProcessIdleTtlMs))
        return false;
      if (this.remoteProcessIdleTtlMs != that.remoteProcessIdleTtlMs)
        return false;
    }

    boolean this_present_verboseProcessing = true;
    boolean that_present_verboseProcessing = true;
    if (this_present_verboseProcessing || that_present_verboseProcessing) {
      if (!(this_present_verboseProcessing && that_present_verboseProcessing))
        return false;
      if (this.verboseProcessing != that.verboseProcessing)
        return false;
    }

    boolean this_present_properties = true && this.isSetProperties();
    boolean that_present_properties = true && that.isSetProperties();
    if (this_present_properties || that_present_properties) {
      if (!(this_present_properties && that_present_properties))
        return false;
      if (!this.properties.equals(that.properties))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(remoteProcessIdleTtlMs);

    hashCode = hashCode * 8191 + ((verboseProcessing) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetProperties()) ? 131071 : 524287);
    if (isSetProperties())
      hashCode = hashCode * 8191 + properties.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ThriftExecutionSettings other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetRemoteProcessIdleTtlMs(), other.isSetRemoteProcessIdleTtlMs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRemoteProcessIdleTtlMs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.remoteProcessIdleTtlMs, other.remoteProcessIdleTtlMs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVerboseProcessing(), other.isSetVerboseProcessing());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVerboseProcessing()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.verboseProcessing, other.verboseProcessing);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetProperties(), other.isSetProperties());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProperties()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.properties, other.properties);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftExecutionSettings(");
    boolean first = true;

    sb.append("remoteProcessIdleTtlMs:");
    sb.append(this.remoteProcessIdleTtlMs);
    first = false;
    if (!first) sb.append(", ");
    sb.append("verboseProcessing:");
    sb.append(this.verboseProcessing);
    first = false;
    if (!first) sb.append(", ");
    sb.append("properties:");
    if (this.properties == null) {
      sb.append("null");
    } else {
      sb.append(this.properties);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'remoteProcessIdleTtlMs' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'verboseProcessing' because it's a primitive and you chose the non-beans generator.
    if (properties == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'properties' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftExecutionSettingsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftExecutionSettingsStandardScheme getScheme() {
      return new ThriftExecutionSettingsStandardScheme();
    }
  }

  private static class ThriftExecutionSettingsStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftExecutionSettings> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftExecutionSettings struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // REMOTE_PROCESS_IDLE_TTL_MS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.remoteProcessIdleTtlMs = iprot.readI64();
              struct.setRemoteProcessIdleTtlMsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VERBOSE_PROCESSING
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.verboseProcessing = iprot.readBool();
              struct.setVerboseProcessingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PROPERTIES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map70 = iprot.readMapBegin();
                struct.properties = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map70.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key71;
                @org.apache.thrift.annotation.Nullable java.lang.String _val72;
                for (int _i73 = 0; _i73 < _map70.size; ++_i73)
                {
                  _key71 = iprot.readString();
                  _val72 = iprot.readString();
                  struct.properties.put(_key71, _val72);
                }
                iprot.readMapEnd();
              }
              struct.setPropertiesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetRemoteProcessIdleTtlMs()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'remoteProcessIdleTtlMs' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetVerboseProcessing()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'verboseProcessing' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftExecutionSettings struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(REMOTE_PROCESS_IDLE_TTL_MS_FIELD_DESC);
      oprot.writeI64(struct.remoteProcessIdleTtlMs);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(VERBOSE_PROCESSING_FIELD_DESC);
      oprot.writeBool(struct.verboseProcessing);
      oprot.writeFieldEnd();
      if (struct.properties != null) {
        oprot.writeFieldBegin(PROPERTIES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.properties.size()));
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter74 : struct.properties.entrySet())
          {
            oprot.writeString(_iter74.getKey());
            oprot.writeString(_iter74.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftExecutionSettingsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftExecutionSettingsTupleScheme getScheme() {
      return new ThriftExecutionSettingsTupleScheme();
    }
  }

  private static class ThriftExecutionSettingsTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftExecutionSettings> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftExecutionSettings struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.remoteProcessIdleTtlMs);
      oprot.writeBool(struct.verboseProcessing);
      {
        oprot.writeI32(struct.properties.size());
        for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter75 : struct.properties.entrySet())
        {
          oprot.writeString(_iter75.getKey());
          oprot.writeString(_iter75.getValue());
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftExecutionSettings struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.remoteProcessIdleTtlMs = iprot.readI64();
      struct.setRemoteProcessIdleTtlMsIsSet(true);
      struct.verboseProcessing = iprot.readBool();
      struct.setVerboseProcessingIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map76 = iprot.readMapBegin(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING); 
        struct.properties = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map76.size);
        @org.apache.thrift.annotation.Nullable java.lang.String _key77;
        @org.apache.thrift.annotation.Nullable java.lang.String _val78;
        for (int _i79 = 0; _i79 < _map76.size; ++_i79)
        {
          _key77 = iprot.readString();
          _val78 = iprot.readString();
          struct.properties.put(_key77, _val78);
        }
      }
      struct.setPropertiesIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

