/**
 * Autogenerated by Thrift Compiler (0.21.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package consulo.externalSystem.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ThriftProjectData implements org.apache.thrift.TBase<ThriftProjectData, ThriftProjectData._Fields>, java.io.Serializable, Cloneable, Comparable<ThriftProjectData> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ThriftProjectData");

  private static final org.apache.thrift.protocol.TField EXTERNAL_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("externalName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField INTERNAL_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("internalName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField OWNER_FIELD_DESC = new org.apache.thrift.protocol.TField("owner", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField LINKED_EXTERNAL_PROJECT_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("linkedExternalProjectPath", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField IDE_PROJECT_FILE_DIRECTORY_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("ideProjectFileDirectoryPath", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ThriftProjectDataStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ThriftProjectDataTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String externalName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String internalName; // required
  public @org.apache.thrift.annotation.Nullable ThriftProjectSystemId owner; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String linkedExternalProjectPath; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String ideProjectFileDirectoryPath; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EXTERNAL_NAME((short)1, "externalName"),
    INTERNAL_NAME((short)2, "internalName"),
    OWNER((short)3, "owner"),
    LINKED_EXTERNAL_PROJECT_PATH((short)4, "linkedExternalProjectPath"),
    IDE_PROJECT_FILE_DIRECTORY_PATH((short)5, "ideProjectFileDirectoryPath");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EXTERNAL_NAME
          return EXTERNAL_NAME;
        case 2: // INTERNAL_NAME
          return INTERNAL_NAME;
        case 3: // OWNER
          return OWNER;
        case 4: // LINKED_EXTERNAL_PROJECT_PATH
          return LINKED_EXTERNAL_PROJECT_PATH;
        case 5: // IDE_PROJECT_FILE_DIRECTORY_PATH
          return IDE_PROJECT_FILE_DIRECTORY_PATH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.IDE_PROJECT_FILE_DIRECTORY_PATH};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EXTERNAL_NAME, new org.apache.thrift.meta_data.FieldMetaData("externalName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.INTERNAL_NAME, new org.apache.thrift.meta_data.FieldMetaData("internalName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OWNER, new org.apache.thrift.meta_data.FieldMetaData("owner", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ThriftProjectSystemId.class)));
    tmpMap.put(_Fields.LINKED_EXTERNAL_PROJECT_PATH, new org.apache.thrift.meta_data.FieldMetaData("linkedExternalProjectPath", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IDE_PROJECT_FILE_DIRECTORY_PATH, new org.apache.thrift.meta_data.FieldMetaData("ideProjectFileDirectoryPath", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ThriftProjectData.class, metaDataMap);
  }

  public ThriftProjectData() {
  }

  public ThriftProjectData(
    java.lang.String externalName,
    java.lang.String internalName,
    ThriftProjectSystemId owner,
    java.lang.String linkedExternalProjectPath)
  {
    this();
    this.externalName = externalName;
    this.internalName = internalName;
    this.owner = owner;
    this.linkedExternalProjectPath = linkedExternalProjectPath;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ThriftProjectData(ThriftProjectData other) {
    if (other.isSetExternalName()) {
      this.externalName = other.externalName;
    }
    if (other.isSetInternalName()) {
      this.internalName = other.internalName;
    }
    if (other.isSetOwner()) {
      this.owner = new ThriftProjectSystemId(other.owner);
    }
    if (other.isSetLinkedExternalProjectPath()) {
      this.linkedExternalProjectPath = other.linkedExternalProjectPath;
    }
    if (other.isSetIdeProjectFileDirectoryPath()) {
      this.ideProjectFileDirectoryPath = other.ideProjectFileDirectoryPath;
    }
  }

  @Override
  public ThriftProjectData deepCopy() {
    return new ThriftProjectData(this);
  }

  @Override
  public void clear() {
    this.externalName = null;
    this.internalName = null;
    this.owner = null;
    this.linkedExternalProjectPath = null;
    this.ideProjectFileDirectoryPath = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getExternalName() {
    return this.externalName;
  }

  public ThriftProjectData setExternalName(@org.apache.thrift.annotation.Nullable java.lang.String externalName) {
    this.externalName = externalName;
    return this;
  }

  public void unsetExternalName() {
    this.externalName = null;
  }

  /** Returns true if field externalName is set (has been assigned a value) and false otherwise */
  public boolean isSetExternalName() {
    return this.externalName != null;
  }

  public void setExternalNameIsSet(boolean value) {
    if (!value) {
      this.externalName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getInternalName() {
    return this.internalName;
  }

  public ThriftProjectData setInternalName(@org.apache.thrift.annotation.Nullable java.lang.String internalName) {
    this.internalName = internalName;
    return this;
  }

  public void unsetInternalName() {
    this.internalName = null;
  }

  /** Returns true if field internalName is set (has been assigned a value) and false otherwise */
  public boolean isSetInternalName() {
    return this.internalName != null;
  }

  public void setInternalNameIsSet(boolean value) {
    if (!value) {
      this.internalName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ThriftProjectSystemId getOwner() {
    return this.owner;
  }

  public ThriftProjectData setOwner(@org.apache.thrift.annotation.Nullable ThriftProjectSystemId owner) {
    this.owner = owner;
    return this;
  }

  public void unsetOwner() {
    this.owner = null;
  }

  /** Returns true if field owner is set (has been assigned a value) and false otherwise */
  public boolean isSetOwner() {
    return this.owner != null;
  }

  public void setOwnerIsSet(boolean value) {
    if (!value) {
      this.owner = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getLinkedExternalProjectPath() {
    return this.linkedExternalProjectPath;
  }

  public ThriftProjectData setLinkedExternalProjectPath(@org.apache.thrift.annotation.Nullable java.lang.String linkedExternalProjectPath) {
    this.linkedExternalProjectPath = linkedExternalProjectPath;
    return this;
  }

  public void unsetLinkedExternalProjectPath() {
    this.linkedExternalProjectPath = null;
  }

  /** Returns true if field linkedExternalProjectPath is set (has been assigned a value) and false otherwise */
  public boolean isSetLinkedExternalProjectPath() {
    return this.linkedExternalProjectPath != null;
  }

  public void setLinkedExternalProjectPathIsSet(boolean value) {
    if (!value) {
      this.linkedExternalProjectPath = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getIdeProjectFileDirectoryPath() {
    return this.ideProjectFileDirectoryPath;
  }

  public ThriftProjectData setIdeProjectFileDirectoryPath(@org.apache.thrift.annotation.Nullable java.lang.String ideProjectFileDirectoryPath) {
    this.ideProjectFileDirectoryPath = ideProjectFileDirectoryPath;
    return this;
  }

  public void unsetIdeProjectFileDirectoryPath() {
    this.ideProjectFileDirectoryPath = null;
  }

  /** Returns true if field ideProjectFileDirectoryPath is set (has been assigned a value) and false otherwise */
  public boolean isSetIdeProjectFileDirectoryPath() {
    return this.ideProjectFileDirectoryPath != null;
  }

  public void setIdeProjectFileDirectoryPathIsSet(boolean value) {
    if (!value) {
      this.ideProjectFileDirectoryPath = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case EXTERNAL_NAME:
      if (value == null) {
        unsetExternalName();
      } else {
        setExternalName((java.lang.String)value);
      }
      break;

    case INTERNAL_NAME:
      if (value == null) {
        unsetInternalName();
      } else {
        setInternalName((java.lang.String)value);
      }
      break;

    case OWNER:
      if (value == null) {
        unsetOwner();
      } else {
        setOwner((ThriftProjectSystemId)value);
      }
      break;

    case LINKED_EXTERNAL_PROJECT_PATH:
      if (value == null) {
        unsetLinkedExternalProjectPath();
      } else {
        setLinkedExternalProjectPath((java.lang.String)value);
      }
      break;

    case IDE_PROJECT_FILE_DIRECTORY_PATH:
      if (value == null) {
        unsetIdeProjectFileDirectoryPath();
      } else {
        setIdeProjectFileDirectoryPath((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case EXTERNAL_NAME:
      return getExternalName();

    case INTERNAL_NAME:
      return getInternalName();

    case OWNER:
      return getOwner();

    case LINKED_EXTERNAL_PROJECT_PATH:
      return getLinkedExternalProjectPath();

    case IDE_PROJECT_FILE_DIRECTORY_PATH:
      return getIdeProjectFileDirectoryPath();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case EXTERNAL_NAME:
      return isSetExternalName();
    case INTERNAL_NAME:
      return isSetInternalName();
    case OWNER:
      return isSetOwner();
    case LINKED_EXTERNAL_PROJECT_PATH:
      return isSetLinkedExternalProjectPath();
    case IDE_PROJECT_FILE_DIRECTORY_PATH:
      return isSetIdeProjectFileDirectoryPath();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ThriftProjectData)
      return this.equals((ThriftProjectData)that);
    return false;
  }

  public boolean equals(ThriftProjectData that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_externalName = true && this.isSetExternalName();
    boolean that_present_externalName = true && that.isSetExternalName();
    if (this_present_externalName || that_present_externalName) {
      if (!(this_present_externalName && that_present_externalName))
        return false;
      if (!this.externalName.equals(that.externalName))
        return false;
    }

    boolean this_present_internalName = true && this.isSetInternalName();
    boolean that_present_internalName = true && that.isSetInternalName();
    if (this_present_internalName || that_present_internalName) {
      if (!(this_present_internalName && that_present_internalName))
        return false;
      if (!this.internalName.equals(that.internalName))
        return false;
    }

    boolean this_present_owner = true && this.isSetOwner();
    boolean that_present_owner = true && that.isSetOwner();
    if (this_present_owner || that_present_owner) {
      if (!(this_present_owner && that_present_owner))
        return false;
      if (!this.owner.equals(that.owner))
        return false;
    }

    boolean this_present_linkedExternalProjectPath = true && this.isSetLinkedExternalProjectPath();
    boolean that_present_linkedExternalProjectPath = true && that.isSetLinkedExternalProjectPath();
    if (this_present_linkedExternalProjectPath || that_present_linkedExternalProjectPath) {
      if (!(this_present_linkedExternalProjectPath && that_present_linkedExternalProjectPath))
        return false;
      if (!this.linkedExternalProjectPath.equals(that.linkedExternalProjectPath))
        return false;
    }

    boolean this_present_ideProjectFileDirectoryPath = true && this.isSetIdeProjectFileDirectoryPath();
    boolean that_present_ideProjectFileDirectoryPath = true && that.isSetIdeProjectFileDirectoryPath();
    if (this_present_ideProjectFileDirectoryPath || that_present_ideProjectFileDirectoryPath) {
      if (!(this_present_ideProjectFileDirectoryPath && that_present_ideProjectFileDirectoryPath))
        return false;
      if (!this.ideProjectFileDirectoryPath.equals(that.ideProjectFileDirectoryPath))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetExternalName()) ? 131071 : 524287);
    if (isSetExternalName())
      hashCode = hashCode * 8191 + externalName.hashCode();

    hashCode = hashCode * 8191 + ((isSetInternalName()) ? 131071 : 524287);
    if (isSetInternalName())
      hashCode = hashCode * 8191 + internalName.hashCode();

    hashCode = hashCode * 8191 + ((isSetOwner()) ? 131071 : 524287);
    if (isSetOwner())
      hashCode = hashCode * 8191 + owner.hashCode();

    hashCode = hashCode * 8191 + ((isSetLinkedExternalProjectPath()) ? 131071 : 524287);
    if (isSetLinkedExternalProjectPath())
      hashCode = hashCode * 8191 + linkedExternalProjectPath.hashCode();

    hashCode = hashCode * 8191 + ((isSetIdeProjectFileDirectoryPath()) ? 131071 : 524287);
    if (isSetIdeProjectFileDirectoryPath())
      hashCode = hashCode * 8191 + ideProjectFileDirectoryPath.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ThriftProjectData other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetExternalName(), other.isSetExternalName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExternalName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.externalName, other.externalName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetInternalName(), other.isSetInternalName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInternalName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.internalName, other.internalName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOwner(), other.isSetOwner());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOwner()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.owner, other.owner);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLinkedExternalProjectPath(), other.isSetLinkedExternalProjectPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLinkedExternalProjectPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.linkedExternalProjectPath, other.linkedExternalProjectPath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIdeProjectFileDirectoryPath(), other.isSetIdeProjectFileDirectoryPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdeProjectFileDirectoryPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ideProjectFileDirectoryPath, other.ideProjectFileDirectoryPath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ThriftProjectData(");
    boolean first = true;

    sb.append("externalName:");
    if (this.externalName == null) {
      sb.append("null");
    } else {
      sb.append(this.externalName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("internalName:");
    if (this.internalName == null) {
      sb.append("null");
    } else {
      sb.append(this.internalName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("owner:");
    if (this.owner == null) {
      sb.append("null");
    } else {
      sb.append(this.owner);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("linkedExternalProjectPath:");
    if (this.linkedExternalProjectPath == null) {
      sb.append("null");
    } else {
      sb.append(this.linkedExternalProjectPath);
    }
    first = false;
    if (isSetIdeProjectFileDirectoryPath()) {
      if (!first) sb.append(", ");
      sb.append("ideProjectFileDirectoryPath:");
      if (this.ideProjectFileDirectoryPath == null) {
        sb.append("null");
      } else {
        sb.append(this.ideProjectFileDirectoryPath);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (externalName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'externalName' was not present! Struct: " + toString());
    }
    if (internalName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'internalName' was not present! Struct: " + toString());
    }
    if (owner == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'owner' was not present! Struct: " + toString());
    }
    if (linkedExternalProjectPath == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'linkedExternalProjectPath' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (owner != null) {
      owner.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ThriftProjectDataStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftProjectDataStandardScheme getScheme() {
      return new ThriftProjectDataStandardScheme();
    }
  }

  private static class ThriftProjectDataStandardScheme extends org.apache.thrift.scheme.StandardScheme<ThriftProjectData> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ThriftProjectData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EXTERNAL_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.externalName = iprot.readString();
              struct.setExternalNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // INTERNAL_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.internalName = iprot.readString();
              struct.setInternalNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OWNER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.owner = new ThriftProjectSystemId();
              struct.owner.read(iprot);
              struct.setOwnerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LINKED_EXTERNAL_PROJECT_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.linkedExternalProjectPath = iprot.readString();
              struct.setLinkedExternalProjectPathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // IDE_PROJECT_FILE_DIRECTORY_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ideProjectFileDirectoryPath = iprot.readString();
              struct.setIdeProjectFileDirectoryPathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ThriftProjectData struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.externalName != null) {
        oprot.writeFieldBegin(EXTERNAL_NAME_FIELD_DESC);
        oprot.writeString(struct.externalName);
        oprot.writeFieldEnd();
      }
      if (struct.internalName != null) {
        oprot.writeFieldBegin(INTERNAL_NAME_FIELD_DESC);
        oprot.writeString(struct.internalName);
        oprot.writeFieldEnd();
      }
      if (struct.owner != null) {
        oprot.writeFieldBegin(OWNER_FIELD_DESC);
        struct.owner.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.linkedExternalProjectPath != null) {
        oprot.writeFieldBegin(LINKED_EXTERNAL_PROJECT_PATH_FIELD_DESC);
        oprot.writeString(struct.linkedExternalProjectPath);
        oprot.writeFieldEnd();
      }
      if (struct.ideProjectFileDirectoryPath != null) {
        if (struct.isSetIdeProjectFileDirectoryPath()) {
          oprot.writeFieldBegin(IDE_PROJECT_FILE_DIRECTORY_PATH_FIELD_DESC);
          oprot.writeString(struct.ideProjectFileDirectoryPath);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ThriftProjectDataTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ThriftProjectDataTupleScheme getScheme() {
      return new ThriftProjectDataTupleScheme();
    }
  }

  private static class ThriftProjectDataTupleScheme extends org.apache.thrift.scheme.TupleScheme<ThriftProjectData> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ThriftProjectData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.externalName);
      oprot.writeString(struct.internalName);
      struct.owner.write(oprot);
      oprot.writeString(struct.linkedExternalProjectPath);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIdeProjectFileDirectoryPath()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetIdeProjectFileDirectoryPath()) {
        oprot.writeString(struct.ideProjectFileDirectoryPath);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ThriftProjectData struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.externalName = iprot.readString();
      struct.setExternalNameIsSet(true);
      struct.internalName = iprot.readString();
      struct.setInternalNameIsSet(true);
      struct.owner = new ThriftProjectSystemId();
      struct.owner.read(iprot);
      struct.setOwnerIsSet(true);
      struct.linkedExternalProjectPath = iprot.readString();
      struct.setLinkedExternalProjectPathIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.ideProjectFileDirectoryPath = iprot.readString();
        struct.setIdeProjectFileDirectoryPathIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

