name: jdk24

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 24
      uses: actions/setup-java@v1
      with:
        distribution: 'temurin'
        java-version: 24
    - name: Build with Maven
      run: mvn -X -U -T 1C -Dmaven.javadoc.skip=true -B -V clean package
